<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__form_detalleSolicitudViaticotablaProduct_50f147</name>
   <tag></tag>
   <elementGuidId>7aa7f026-b2b7-45f7-9223-dea5612fc6cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[16]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a59b69d3-e175-40b0-8c46-929500ab9cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:j_idt206</value>
      <webElementGuid>d24503bd-07b7-430e-9f40-88ccb53b909d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1245f949-b8ad-4306-9a43-2a0a290c296e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn-miniadicionar</value>
      <webElementGuid>f14b04d7-63ae-4d40-a915-3292dcca6e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:j_idt206&quot;,f:&quot;form_detalleSolicitudViatico&quot;,u:&quot;areaAplicacion&quot;,onco:function(xhr,status,args,data){resizeWindowIFrame();;}});return false;</value>
      <webElementGuid>885afd58-5599-4fd1-9dbb-5cf74812be9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:j_idt206&quot;)</value>
      <webElementGuid>4dad3e8c-cbc9-411b-bb57-7dccf6ec6b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/SolicitarViatico/iframe_Codigo QR_911a2456a5b74376e050007f01005e0b</value>
      <webElementGuid>ce7abbe8-4274-4179-ae39-112f46dc7151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:j_idt206']</value>
      <webElementGuid>03667a26-1ea4-479e-9e8e-f114e9de5a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tfoot[@id='form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion_foot']/tr/td[16]/a</value>
      <webElementGuid>b3fe1d1c-ea25-43fa-b9b6-ec459694557f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>736fea60-74f9-44e3-9203-fce41bcffabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[16]/a</value>
      <webElementGuid>baf99b47-21a3-459c-9eaa-e40f68ad10b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:j_idt206' and @href = '#']</value>
      <webElementGuid>92cd539f-6b72-4949-afbd-e40cdaae52a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
