<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_No se encontraron registros_form_detalleS_3de8da</name>
   <tag></tag>
   <elementGuidId>e453a54e-cb79-46fa-bd77-2d74a0c02158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div/div[2]/div/form[1]/table/tbody/tr[3]/td/div/div[1]/table/tbody/tr[11]/td/table/tbody/tr/td/table/tbody/tr[2]/td/div[1]/div/table/tfoot/tr/td[1]/table/tbody/tr[1]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>568a3475-cd37-4e36-87d2-dc3aa7e638bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_detalleSolicitudViatico:tablaProductos:10:tablaCostos:j_idt247</value>
      <webElementGuid>665a1caa-60b2-4e0e-8119-b83bafca0bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a41b5faf-4cca-490a-b40e-bdc14864da04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn_popupInformacion</value>
      <webElementGuid>0187f22c-b1ed-409f-a43b-be6aab703c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>buscaPosicion(this.id);;PrimeFaces.ab({s:&quot;form_detalleSolicitudViatico:tablaProductos:10:tablaCostos:j_idt247&quot;,f:&quot;form_detalleSolicitudViatico&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>fa39bab3-dc20-4267-86f7-b21b4eb4b4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_detalleSolicitudViatico:tablaProductos:10:tablaCostos:j_idt247&quot;)</value>
      <webElementGuid>9d0afe5b-ab40-4ab7-816d-124d59216d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/SolicitarViatico/iframe_Codigo QR_911a2456a5b74376e050007f01005e0b</value>
      <webElementGuid>f2673f55-ed13-4d87-9334-67bd9cc1b072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_detalleSolicitudViatico:tablaProductos:10:tablaCostos:j_idt247']</value>
      <webElementGuid>14e698d3-8e3f-4ca0-94f6-b8e43ad0615a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tfoot[@id='form_detalleSolicitudViatico:tablaProductos:10:tablaCostos_foot']/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>a9dbd218-5d39-4f61-b673-601935c58bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>9f7647ab-f1bd-40d4-9c34-796701eef89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>0a6f2266-332c-40a2-a652-345101939ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_detalleSolicitudViatico:tablaProductos:10:tablaCostos:j_idt247' and @href = '#']</value>
      <webElementGuid>b60512dc-b919-49e6-a3ba-892a80ba1244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
