<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HoraSalida</name>
   <tag></tag>
   <elementGuidId>6ef2080d-60b0-4b49-9584-4e7e8be9ab19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:horaInicial_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad870070-7024-498c-b0d7-cf90c8bba449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:horaInicial</value>
      <webElementGuid>5c978798-f133-47b0-8b67-5b7fe01c8da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe16e8c6-af70-4631-8852-4014adefe357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:horaInicial</value>
      <webElementGuid>da438769-2be6-44be-82d0-16535bd3e8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>4bbb6d6d-9acf-4842-83ef-977ef45b2603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>d120eb30-f6c0-4a75-ab07-72172c41c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>acd0ad41-3bc2-47bf-b1af-856ee00b39fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>aaca8811-bebb-4337-932d-f533e29e9c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:horaInicial&quot;)</value>
      <webElementGuid>b05e8de5-fb21-4809-9076-fc0ae3148357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/SolicitarViatico/iframe_Codigo QR_911a2456a5b74376e050007f01005e0b</value>
      <webElementGuid>3ec817fb-0834-46e5-bed8-2e31d693d437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:horaInicial']</value>
      <webElementGuid>c945aeb1-6dd8-43cf-9b7f-6d0b36bbcaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tfoot[@id='form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion_foot']/tr/td[5]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>17138889-657d-46c2-a6f6-8374c5b8ed28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>72e8611d-8622-4a2c-9a45-bbd8a8959679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:horaInicial' and @type = 'text' and @name = 'form_detalleSolicitudViatico:tablaProductos:9:tablaProgramacion:horaInicial']</value>
      <webElementGuid>e3887278-4479-4fd7-839f-a0cbe4ac0485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
