<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mis solicitudViatico</name>
   <tag></tag>
   <elementGuidId>28452d29-dbb9-433c-858b-5d84cce42cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div[1]/div/div[2]/div/div[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>730b664c-ace1-416b-ba48-8986919f09df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solicitud Viaticos</value>
      <webElementGuid>fafc7bd1-35e8-4662-ac9e-a6466c45d398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;us-interfaz-7vsk&quot;)/div[@class=&quot;panel-heading&quot;]/label[1]</value>
      <webElementGuid>a1437639-9f63-49c1-85ce-f3912fbb9ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='us-interfaz-7vsk']/div/label</value>
      <webElementGuid>acf0695c-33c2-40ed-bdd1-0f0a9693da17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro'])[1]/preceding::label[1]</value>
      <webElementGuid>e5b53f9e-a349-4c60-9fcf-fe7779bda802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitado'])[1]/preceding::label[1]</value>
      <webElementGuid>675051df-882a-4203-af53-528a2ac6a51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solicitud Viaticos']/parent::*</value>
      <webElementGuid>822156b7-7002-450b-892e-a18a2f95249f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>228c11bc-bbde-46c7-893e-efbc475f1426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Solicitud Viaticos' or . = 'Solicitud Viaticos')]</value>
      <webElementGuid>d48ab787-d93e-45c3-9260-57a650e93163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
