<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Solicitud Viaticos</name>
   <tag></tag>
   <elementGuidId>28452d29-dbb9-433c-858b-5d84cce42cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>
/html/body/div[1]/div/div/div/div[1]/div/div[2]/div/div[11]/div/figure/figcaption/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>aa8a0ac4-5f0e-4252-b4b3-93312e22b4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solicitud Viaticos</value>
      <webElementGuid>29717f65-d7c4-411e-99b1-86346a54229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;us-interfaz-7vsk&quot;)/div[@class=&quot;panel-heading&quot;]/label[1]</value>
      <webElementGuid>533af278-a2a2-4a88-821b-1b63313a9ee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='us-interfaz-7vsk']/div/label</value>
      <webElementGuid>03873472-12e6-4fb2-b570-45b1fcb13103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro'])[1]/preceding::label[1]</value>
      <webElementGuid>db54d58e-db78-4ca2-9d65-06b4579ab577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitado'])[1]/preceding::label[1]</value>
      <webElementGuid>bea7edbe-ef8c-4742-bfa1-d77bd284f831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solicitud Viaticos']/parent::*</value>
      <webElementGuid>faf9acd4-1509-42f6-afff-f3ece2ccc3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>7a197ee8-7c39-4378-83c3-14df8460cdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Solicitud Viaticos' or . = 'Solicitud Viaticos')]</value>
      <webElementGuid>7e36b6ea-e9c4-4ac1-ac37-416f7692a071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
