<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ejecutar</name>
   <tag></tag>
   <elementGuidId>96176d17-941a-443f-bca3-f7d0c2a6a51b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Ejecutar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.us-boton.btn-filtrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c76969e-add2-440c-abd5-8deebdd4b72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7a0baea0-bb2b-4be8-bafa-cc307d07dd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('formImportarFuente'),{'formImportarFuente:j_idt4271':'formImportarFuente:j_idt4271'},'');return false</value>
      <webElementGuid>07e7a955-4033-4c01-9d4f-aea5e11a5362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-boton btn-filtrar</value>
      <webElementGuid>7a7a9bf0-e923-4176-9b9b-979c03273d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ejecutar</value>
      <webElementGuid>8932db04-0e2e-4bba-8bf1-ad895892ecc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formImportarFuente:DATOS&quot;)/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/a[@class=&quot;us-boton btn-filtrar&quot;]</value>
      <webElementGuid>123a3185-973f-4b7e-8aad-ac29553c7f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/CargueMasivoAplicarNovEmp/iframe_Mis Cesantas_7F07D451F09D6B35813735F_5fd111</value>
      <webElementGuid>8a31f9b4-cd34-4fa5-bbf4-22269a2bd293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('formImportarFuente'),{'formImportarFuente:j_idt4271':'formImportarFuente:j_idt4271'},'');return false&quot;]</value>
      <webElementGuid>87c16718-6641-4177-ba69-82147c18dbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='formImportarFuente:DATOS']/tbody/tr[2]/td/table/tbody/tr/td[3]/a</value>
      <webElementGuid>ab983ace-0e95-4584-bfd0-8656227fb1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ejecutar')]</value>
      <webElementGuid>9eb900cf-5c42-439e-9c40-7d113491de2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::a[3]</value>
      <webElementGuid>806a4446-e242-445d-9887-06e568b7b22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Línea'])[1]/following::a[3]</value>
      <webElementGuid>70ae32d9-9d7c-4248-8e48-a093e4e3c9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ejecutar']/parent::*</value>
      <webElementGuid>55e0ecac-299c-4e63-90ad-bef08c97bbf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>d6787cdf-8b23-44a3-8791-7d955547befb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td[3]/a</value>
      <webElementGuid>00417f0c-6691-4b45-b45d-bbe3e9b9de7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Ejecutar' or . = 'Ejecutar')]</value>
      <webElementGuid>8cd0674d-d7a4-44a0-985c-ff28eb447a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
