<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_No se encontr registros_btn_popupInformacion</name>
   <tag></tag>
   <elementGuidId>3cd6c3b8-8a63-419a-9eea-2a29e4fe6e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn_popupInformacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44e44b05-13fb-44af-b6fc-520774b219d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e74cbe6c-38dd-4142-b2d8-8eea4647c04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('formImportarFuente'),{'formImportarFuente:tabGrupo:tabla_servicios:0:j_idt4213':'formImportarFuente:tabGrupo:tabla_servicios:0:j_idt4213','paramServicio':'co.com.unionsoluciones.fwk.wrapper.FuenteLineaServicioWrapper@50a5c2e0'},'');return false</value>
      <webElementGuid>c5e851b2-75f6-49ee-89f9-3c54d43bd56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_popupInformacion</value>
      <webElementGuid>9596ab83-ecee-428b-80c6-556c196cae9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formImportarFuente:tabGrupo:tabla_servicios&quot;)/tbody[1]/tr[@class=&quot;par&quot;]/td[5]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;btn_popupInformacion&quot;]</value>
      <webElementGuid>40275cb2-ec9c-4da8-b0c3-2c4e484f570e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/CargueMasivoAplicarNovEmp/iframe_Mis Cesantas_7F07D451F09D6B35813735F_5fd111</value>
      <webElementGuid>2cac0c6d-d2a2-47b5-bbcb-cd191281b3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('formImportarFuente'),{'formImportarFuente:tabGrupo:tabla_servicios:0:j_idt4213':'formImportarFuente:tabGrupo:tabla_servicios:0:j_idt4213','paramServicio':'co.com.unionsoluciones.fwk.wrapper.FuenteLineaServicioWrapper@50a5c2e0'},'');return false&quot;]</value>
      <webElementGuid>c87467af-a5c8-4fdc-931c-e0cc7ed6c8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='formImportarFuente:tabGrupo:tabla_servicios']/tbody/tr/td[5]/table/tbody/tr/td/a</value>
      <webElementGuid>25f127be-794e-461e-bff3-7a09e4b13ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>bce7dc7e-45da-43f4-82bf-69073125c272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>d8de1e3e-572d-478a-a576-dd06547cbc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>15e674e2-aace-4978-8ea7-e24cf891a610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
