<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ver_formImportarFuentelistagrupo0j_idt4168</name>
   <tag></tag>
   <elementGuidId>3b6ac962-84ae-48b3-a002-249edd17de1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/table/tbody/tr/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83e1ab2f-610f-4ef5-8c1b-fd3d4dd05577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formImportarFuente:listagrupo:0:j_idt4168</value>
      <webElementGuid>ab4a1c4f-938f-4f5e-a3f5-9e28417f8b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>24ad9b18-be03-4d65-bd36-e6780567a52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.ab(this,event,'action','@this','@form',{'params':{'param':'co.com.unionsoluciones.dinamico.archivo.fuente.GrupoFuente@4cfb3356'}});return false</value>
      <webElementGuid>0f4a94be-fb87-4a4d-8c2e-6a14198e5e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_popupInformacion</value>
      <webElementGuid>811aaa2b-081e-40f2-88d6-ed0b88806f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formImportarFuente:listagrupo:0:j_idt4168&quot;)</value>
      <webElementGuid>6bfeafb9-ec42-489a-9ec7-e0f9a017507c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/CargueMasivoAplicarNovEmp/iframe_Mis Cesantas_7F07D451F09D6B35813735F_5fd111</value>
      <webElementGuid>2947375f-5c28-4343-bba7-c3cfd22c1d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formImportarFuente:listagrupo:0:j_idt4168']</value>
      <webElementGuid>02fd820f-59cc-49a5-8a4d-7e855b101c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formImportarFuente:listagrupo_data']/tr/td[4]/a</value>
      <webElementGuid>67c5f295-5888-454f-a17d-830ea9abb5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>1dbf4e12-09aa-4014-967f-438b4733eb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[4]/a</value>
      <webElementGuid>d6df80dd-19b0-42c4-8cbe-cbd950ebef96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formImportarFuente:listagrupo:0:j_idt4168' and @href = '#']</value>
      <webElementGuid>ce69833b-0539-4113-89bc-a282bccedeaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
