<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>49c40ff2-cb6f-4a32-9798-4be5cff10642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='formImportarFuente:idPanelMotor']/tbody/tr[3]/td/table/tbody/tr/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36cdb144-9a5e-4a70-9d28-ee81a205019e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>titulo_campo</value>
      <webElementGuid>1225ff72-a2f1-4faf-9fb0-23ec7f7ab47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9c4c345a-35a1-4d1d-9a7f-622879aaa89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formImportarFuente:idPanelMotor&quot;)/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/span[@class=&quot;titulo_campo&quot;]</value>
      <webElementGuid>58bf07b8-7164-4c13-8cae-7e9b7c934b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/CargueMasivoAplicarNovEmp/iframe_Mis Cesantas_7F07D451F09D6B35813735F_5fd111</value>
      <webElementGuid>2c369599-1c20-408b-968c-3a74b668968e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='formImportarFuente:idPanelMotor']/tbody/tr[3]/td/table/tbody/tr/td[2]/span</value>
      <webElementGuid>2ef39384-ea15-44fd-baea-8ce88f1ed3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad linea sin mensaje :'])[1]/following::span[1]</value>
      <webElementGuid>d6de9c6e-9a67-4778-80e2-1deb56d9f45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::span[2]</value>
      <webElementGuid>4604bada-7331-4d74-b50e-7ac385f4cda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad linea con mensaje :'])[1]/preceding::span[1]</value>
      <webElementGuid>66e59026-fedf-4aee-b8ae-698bbf827e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td[2]/span</value>
      <webElementGuid>aafe5848-17bd-4476-853f-5463dc4ed57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>7f6b65b6-31fd-49d0-826e-ca921758bf89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
