<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_parametroscontrato</name>
   <tag></tag>
   <elementGuidId>84f87596-d241-4c66-9416-0803405fa579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='formImportarFuente:tabGrupo:tabla_Parametros_data']/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1f203b1f-dc93-4685-9350-dcfba8f62994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>8ed53141-e076-41ee-8205-6c3c2245ef1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>parametros:contrato</value>
      <webElementGuid>00f19ad7-e279-4ee2-aaf4-7c8f63e1f210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formImportarFuente:tabGrupo:tabla_Parametros_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even fila_tabla_ace&quot;]/td[1]</value>
      <webElementGuid>b4b71436-711e-4629-9d3c-5cf107c2a8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/CargueMasivoAplicarNovEmp/iframe_Mis Cesantas_7F07D451F09D6B35813735F_5fd111</value>
      <webElementGuid>cd352085-d2cc-475d-8e3b-4a0e7cc236ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='formImportarFuente:tabGrupo:tabla_Parametros_data']/tr/td</value>
      <webElementGuid>e872b36c-a0fd-418c-b24d-6d15e25a5134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor'])[1]/following::td[1]</value>
      <webElementGuid>32f301b8-f844-4635-80ca-2e106f44f52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parámetros'])[1]/following::td[1]</value>
      <webElementGuid>b5aa136a-09e5-44bc-8037-8eebe54436ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='parametros:documento'])[1]/preceding::td[2]</value>
      <webElementGuid>38294116-447c-46f1-955e-3a734bc1c7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='parametros:alterno'])[1]/preceding::td[4]</value>
      <webElementGuid>8602b251-7a70-4a7b-baa7-931ba6f85472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='parametros:contrato']/parent::*</value>
      <webElementGuid>77ec6065-5d6c-43c6-b566-a54652a85bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/table/tbody/tr/td[2]/div/div[2]/table/tbody/tr/td</value>
      <webElementGuid>4e386957-962f-45bd-86be-fa7d05092203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'parametros:contrato' or . = 'parametros:contrato')]</value>
      <webElementGuid>fd38e689-dfa4-46c7-92fe-4980c62e698a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
