<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tipo Beneficio_form_listadoBeneficioj_idt69</name>
   <tag></tag>
   <elementGuidId>efad8161-ede0-4ebe-aef3-fdc0ec6720dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
/html/body/div[1]/div[3]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form[1]/table/tbody/tr[1]/td/div/div[2]/table[1]/tbody/tr[1]/td[4]/table/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7798790f-cdab-4400-be90-c805ac5009f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_listadoBeneficio:j_idt69</value>
      <webElementGuid>23d0d1dc-2f2b-43dd-92dc-51f273799a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>eb8ffffd-2020-4b7c-8b6b-09540d32cd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn_popupInformacion</value>
      <webElementGuid>9d5c0fe8-1951-4239-b3ec-e88d873607f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_listadoBeneficio:j_idt69&quot;,f:&quot;form_listadoBeneficio&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>8f9248a6-1e92-4744-a3d2-c053f84880ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_listadoBeneficio:j_idt69&quot;)</value>
      <webElementGuid>e499c79d-1186-4d1a-b51e-e9371a37b1ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_listadoBeneficio:j_idt69']</value>
      <webElementGuid>1ed29fe2-17d8-4a53-9c61-b0138b24e8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_listadoBeneficio:panelFiltro_content']/table/tbody/tr/td[4]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>267f74de-6438-4eef-8f1a-c8f9d0724f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[79]</value>
      <webElementGuid>048d8546-fdfd-4304-a1ad-6ceba40dbef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>0d9f5907-c14c-4c42-a609-1dde3bd2215e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_listadoBeneficio:j_idt69' and @href = '#']</value>
      <webElementGuid>e5db0307-fe9a-4934-911d-cfed84030baf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
