<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Usuario_recuperacion_clavecapchaImg</name>
   <tag></tag>
   <elementGuidId>1baa7dee-d61e-4391-abb0-e0fcd7965e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='recuperacion_clave:capchaImg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ddef2c4d-4c13-44cf-a2c8-ff9fe447e715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recuperacion_clave:capchaImg</value>
      <webElementGuid>453f4526-06b2-4e0c-b2b7-7820ac62cbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://192.168.2.19:8480/PortalSara/captcha/imagemICUm.jpg</value>
      <webElementGuid>4bfca7b8-5c33-46eb-869a-d72b751448b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90px</value>
      <webElementGuid>0800dc2c-a151-4230-9e96-4a956a33dbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250px</value>
      <webElementGuid>166e5dbc-9163-4f8d-8c32-03150f965cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recuperacion_clave:capchaImg&quot;)</value>
      <webElementGuid>c21ab773-91ca-48bb-a77f-9007a88757f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/Prueba/iframe_Ver ms_7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</value>
      <webElementGuid>621cb0f5-ed40-4942-ba23-04db95640776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='recuperacion_clave:capchaImg']</value>
      <webElementGuid>5db12708-0517-4bb0-bd5c-fac8e001dd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='recuperacion_clave:panelCaptcha']/tbody/tr/td/img</value>
      <webElementGuid>215b3614-d4dc-4a04-971e-6866ebde0577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://192.168.2.19:8480/PortalSara/captcha/imagemICUm.jpg')]</value>
      <webElementGuid>da864f41-0e98-422a-9385-4c8c0871ccba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/img</value>
      <webElementGuid>1368cec0-27fe-444d-92f0-ffa1ca5391e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'recuperacion_clave:capchaImg' and @src = 'http://192.168.2.19:8480/PortalSara/captcha/imagemICUm.jpg']</value>
      <webElementGuid>6c018c26-8ef8-40ce-b8af-66ead755fef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
