<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuario_recuperacion_claverecuperacio_0262ad</name>
   <tag></tag>
   <elementGuidId>8ca830da-b5c4-44c7-98a8-29cfac416870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recuperacion_clave:recuperacionUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eadc099-4a5b-4b28-8c32-4ae5701c2195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recuperacion_clave:recuperacionUsuario</value>
      <webElementGuid>29cbb668-6cc6-458e-bb67-7d1e6a01aaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d06a479-d0de-4df4-ba38-7a7b0888b4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recuperacion_clave:recuperacionUsuario</value>
      <webElementGuid>4bc1ff76-4afd-4f35-984f-1b6432320261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>2cca4178-88d6-4e2d-9fc6-67c4e27cf53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0fe2b678-3c1a-4289-befc-941511067dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recuperacion_clave:recuperacionUsuario&quot;)</value>
      <webElementGuid>a8d4df2f-8e29-4be7-bee2-288dc37187c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/Prueba/iframe_Ver ms_7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</value>
      <webElementGuid>41306e84-6bc5-4d9c-92f7-439fbb95c760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recuperacion_clave:recuperacionUsuario']</value>
      <webElementGuid>a675e989-8468-4e3e-88a3-e6aea686de5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='recuperacion_clave']/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>9aadc284-23e2-4ecf-b10e-3addf3e5a545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>498432f6-2dcd-4de3-84d6-1f6adcbfaaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'recuperacion_clave:recuperacionUsuario' and @type = 'text' and @name = 'recuperacion_clave:recuperacionUsuario']</value>
      <webElementGuid>359806c4-99fd-464d-bb60-05e1e0afd94d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
