<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Acta De Grado   Diploma_form_solicitudesE_bf87f8</name>
   <tag></tag>
   <elementGuidId>9adae247-4e17-4f9f-9edf-10a24a3bde57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//body/div[1]/div/div[2]/div/div[3]/div/form/div/fieldset/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/div/table/tbody/tr/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e9edcf2-6cb7-4edb-86a7-3c150de4c763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_solicitudesEmpleado:listaDocumentos:0:j_idt358</value>
      <webElementGuid>b333434a-2902-4960-b4ca-a4b073281d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>753d5849-70dc-4c5a-8982-17bfb99c6376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn-miniadicionar</value>
      <webElementGuid>25cc3ae6-f475-4cf7-93e6-e0c41886db2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_solicitudesEmpleado:listaDocumentos:0:j_idt358&quot;,f:&quot;form_solicitudesEmpleado&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>9e941d5c-cad2-42cb-88b5-a636883960ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_solicitudesEmpleado:listaDocumentos:0:j_idt358&quot;)</value>
      <webElementGuid>41d0ace5-ecec-481b-a54f-04f0b97adf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/ServicioMisCertificados/GenerarSolicitudCertificadoLaboralBPM/iframe_Mis Cesantas_FB1846019F574996BB0A814_6cece9</value>
      <webElementGuid>30c994fa-3b12-4d5d-a4ae-5934c25d82dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_solicitudesEmpleado:listaDocumentos:0:j_idt358']</value>
      <webElementGuid>890ca68d-1667-49d0-9bc3-24ae9cf6ec51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='form_solicitudesEmpleado:listaDocumentos_data']/tr/td[8]/a</value>
      <webElementGuid>f3414d94-654d-44f1-b93b-7dfc53776d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>643ee22c-d056-4107-8fed-f23ff4744a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>e7590481-cd0d-4853-8909-7fd10f453ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_solicitudesEmpleado:listaDocumentos:0:j_idt358' and @href = '#']</value>
      <webElementGuid>39533376-ff42-4318-b56b-8bc58b4f0a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
