<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Autoriza</name>
   <tag></tag>
   <elementGuidId>8dee7e8c-c819-44e5-9ed5-66ce70a0075c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Autoriza')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8360d3fb-4cf5-4895-80d1-18671e9a5e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actividades_form:TabDatBasEmpresa:j_idt62</value>
      <webElementGuid>dabaadcd-7149-45d2-8971-d529f1f0a2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b10da2fa-0996-4675-bbb2-e85e877fbe1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-autorizar</value>
      <webElementGuid>f234ce65-2ba1-41ba-83cb-b62430075ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;actividades_form:TabDatBasEmpresa:j_idt62&quot;,f:&quot;actividades_form&quot;,u:&quot;actividades_form&quot;});return false;</value>
      <webElementGuid>eb1f0edd-8096-4b43-9f49-006f7aa60a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;actividades_form:TabDatBasEmpresa:j_idt62&quot;,escape:true,header:&quot;confirmar&quot;,message:&quot;Desea confirmar la opción seleccionada ?&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>571deda5-47f6-4748-b6b2-799329a10ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Autoriza</value>
      <webElementGuid>3aa3a102-2923-4c6a-9617-c3166b5737ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actividades_form:TabDatBasEmpresa:j_idt62&quot;)</value>
      <webElementGuid>0c74339f-049f-461a-857c-e88e20105f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/ServicioMisCertificados/GenerarSolicitudCertificadoLaboralBPM/iframe_Mis aprobaciones_7F07D451709D4B45813_70d15d</value>
      <webElementGuid>d1b7a2eb-a0fe-4168-a8ac-e5e92c2049bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actividades_form:TabDatBasEmpresa:j_idt62']</value>
      <webElementGuid>1ca5423c-ace5-417e-abda-4bc4256375f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actividades_form:TabDatBasEmpresa:panelActividadesVigentes']/a</value>
      <webElementGuid>6e22807f-1af4-43d7-a55b-39093dfe645d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Autoriza')]</value>
      <webElementGuid>a2c26789-e709-430b-95f8-ecf2bfe62058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceso'])[1]/following::a[2]</value>
      <webElementGuid>c52054dc-2a6b-454c-82d5-f85074220d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarea:'])[1]/following::a[2]</value>
      <webElementGuid>27bf91c6-4fd2-4a9c-9557-be1373f44d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[3]</value>
      <webElementGuid>a376ff55-d0fa-4ae6-a698-15527d29bec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::a[3]</value>
      <webElementGuid>26688327-6564-44e2-b4b6-b21de3a1cd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Autoriza']/parent::*</value>
      <webElementGuid>c86067fa-b470-4e23-97f7-7cd23944f0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>82c0de62-456b-41fd-9056-ef7b09e65107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>82aeb2b3-947b-4cf4-8a98-250e6990c4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'actividades_form:TabDatBasEmpresa:j_idt62' and @href = '#' and (text() = 'Autoriza' or . = 'Autoriza')]</value>
      <webElementGuid>6abab3cf-cdfe-4283-ade1-ce96a384a4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
