<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>embed</name>
   <tag></tag>
   <elementGuidId>926c2452-2dfe-4327-9416-425144ea28b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>embed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='form_solicitudesEmpleado:idPanelSolicitud']/tbody/tr[6]/td/table/tbody/tr/td/embed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>embed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/PortalSara/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc65c34c36c61c36c33c62c35c34c61c32c61c34c61c33c36c39c37c62c62c31c64c30c65c36c62c62c36c39c34c38c62&amp;B=c53</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>750</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resize_embed()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_solicitudesEmpleado:idPanelSolicitud&quot;)/tbody[1]/tr[6]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/embed[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/ServicioMisCertificados/GenerarSolicitudCertificadoLaboral/iframe_Mis Cesantas_FB1846019F574996BB0A814_6cece9</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_solicitudesEmpleado:idPanelSolicitud']/tbody/tr[6]/td/table/tbody/tr/td/embed</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//embed</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//embed[@src = '/PortalSara/descargaArchivosSeguro?A=c74c6dc70c52c53c5fc65c34c36c61c36c33c62c35c34c61c32c61c34c61c33c36c39c37c62c62c31c64c30c65c36c62c62c36c39c34c38c62&amp;B=c53']</value>
   </webElementXpaths>
</WebElementEntity>
