<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Seleccione--Evaluacin Capacitacin</name>
   <tag></tag>
   <elementGuidId>ab545c79-581e-48c8-b177-6a576b8b3950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:0:ingresoMarca']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ebf0985d-f0a3-4261-bab0-54dc29d7aedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:0:ingresoMarca</value>
      <webElementGuid>6b652598-e57b-45cc-88d1-cbf320a70d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:0:ingresoMarca</value>
      <webElementGuid>aaa3cdb1-0b01-42b5-bd07-05169fef2441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eval_opciones long_mitad_campo</value>
      <webElementGuid>bc282dea-00ce-4ed3-99ea-ecfb83fd9464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9e596aa1-3f10-4e5f-92d2-8b0766438f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	--Seleccione--
	SI
	NO
</value>
      <webElementGuid>8eeac4c8-4b28-49d0-8df8-13a62d66b043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:0:ingresoMarca&quot;)</value>
      <webElementGuid>87e6f11d-e932-49d9-b700-28d4a18fb740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/EvaluarEventoCapacitacion/iframe_Evaluaciones de capacitacin_7F07D451_2549c9</value>
      <webElementGuid>d41f0a2b-b6e9-43dc-a741-f053c152f08b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:0:ingresoMarca']</value>
      <webElementGuid>dd997da7-89d5-47f2-93e5-8180d46f7509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce']/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>3f0b9f14-57e7-4da7-bce8-db67d9e5720c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>3f9f10c9-24ee-4a7b-80d5-ecbecaed404e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿La capacitación cumplió con sus expectativas?'])[1]/following::select[1]</value>
      <webElementGuid>c3990628-6a61-4698-8e2c-f8f4812cc923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Del 1 al 5. ¿Qué tan completo considera que fue la capacitación?'])[1]/preceding::select[1]</value>
      <webElementGuid>2a983e40-9bf2-4b77-abb2-86a1a9a30ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>276f5576-d1e3-4601-94d9-c4b7a640ec9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7f78adf7-99b2-46e0-a4c3-8e37ffe97077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:0:ingresoMarca' and @name = 'form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:0:ingresoMarca' and (text() = '	--Seleccione--
	SI
	NO
' or . = '	--Seleccione--
	SI
	NO
')]</value>
      <webElementGuid>fa197581-4a4a-40e0-b199-709c706a44b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
