<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_filtro_procesoseleccionj_idt73</name>
   <tag></tag>
   <elementGuidId>cd1332db-e525-47b4-85b2-cd696d2fd333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form[1]/span/div[1]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37508080-2d8c-40e0-9a4e-b75de017bac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filtro_procesoseleccion:j_idt73</value>
      <webElementGuid>dad15e49-307b-4362-b24e-7fcbafb6a333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da91ce12-cfff-4004-847e-e60d85e06545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filtro_procesoseleccion:j_idt73</value>
      <webElementGuid>f275d626-573c-478b-8465-7cd938a30d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>0ddd01e6-e950-4ea0-89e9-de59aafa39cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>136e80bd-f1d6-4744-ab85-e6943c886684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ffe71ed2-80fb-4031-899b-d9e22f3074c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;filtro_procesoseleccion&quot;,p:&quot;filtro_procesoseleccion:j_idt73&quot;,u:&quot;filtro_procesoseleccion:tabla&quot;});</value>
      <webElementGuid>d7bb117d-008e-4480-88c3-352dde9f7472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filtro_procesoseleccion:j_idt73&quot;)</value>
      <webElementGuid>d602fbb1-ce83-459c-ba2b-df4422fcb5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filtro_procesoseleccion:j_idt73']</value>
      <webElementGuid>f27e3598-1d66-4ba4-bdeb-9f5db18fcd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filtro_procesoseleccion:formPanel_content']/table/tbody/tr/td[6]/input</value>
      <webElementGuid>8ec1a641-c371-40a6-85e3-56d30c73bcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>4b41398e-54a8-4053-9ae8-89e2b5e9fa3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filtro_procesoseleccion:j_idt73' and @type = 'text' and @name = 'filtro_procesoseleccion:j_idt73']</value>
      <webElementGuid>81c13164-c505-4f4d-951a-839b7a7da308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
