<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ver ms_7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</name>
   <tag></tag>
   <elementGuidId>6176f6e5-b3e2-4c11-93cc-af44dd1ad679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifrm_component_C_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifrm_component_C_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7a701d8a-1271-4775-972d-2a0922fed299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifrm_component_C_0</value>
      <webElementGuid>13e3d362-ba35-4c8b-bdfc-ce7f8f1255d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/PortalSara/webcommonAutoServicio/funcionalidades/login.xhtml?us_id=us-interfaz-tl7d</value>
      <webElementGuid>c7296f5c-6b66-4bf3-b74e-4094b8b6e71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d60518c0-2359-49bd-b30f-aac125890cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</value>
      <webElementGuid>e19fdac6-d2d1-41e9-8319-f069613fdc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0b4bad99-96d7-4ef6-81e2-6f06e5d45aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>da27af7f-7bae-4e39-b519-5ab7eaa0f868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33016078-0e61-450a-b098-93d55c609253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this); </value>
      <webElementGuid>a3119514-94d3-4c09-8e26-77dc44e161dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb7905dc-75b7-4f7e-8262-b779ef92c0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webkitallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bef5a09c-96d3-4644-9220-75f46ece2537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mozallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cf3275d-0455-4952-be2f-838b07e0b968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifrm_component_C_0&quot;)</value>
      <webElementGuid>72e3795b-223c-414b-b2b9-afe102a21508</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifrm_component_C_0']</value>
      <webElementGuid>0762df4e-2176-4825-9ca8-8f7abebe7076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='areaAplicacion']/div[2]/div[2]/div/iframe</value>
      <webElementGuid>1d408412-18f9-4f00-8d9a-d5b198dd8d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>dea55451-2f43-439b-aca4-82f8c7f22a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifrm_component_C_0' and @src = '/PortalSara/webcommonAutoServicio/funcionalidades/login.xhtml?us_id=us-interfaz-tl7d' and @name = '7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx']</value>
      <webElementGuid>0270b783-9c87-475d-aa1c-ceddbba48b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
