<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_entradas</name>
   <tag></tag>
   <elementGuidId>3b70cce1-9905-4c1a-b936-a8ee87b33a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.us-head-popup.us-popup-img > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popupEntradaReporteVisor_form:dialogPopupEntradaReporte_content']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d4814c52-55bc-4124-8641-e4f0e97e418d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>��entradas!!</value>
      <webElementGuid>402094fe-1592-48a6-9a2d-ce3de19113f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupEntradaReporteVisor_form:dialogPopupEntradaReporte_content&quot;)/div[@class=&quot;us-head-popup us-popup-img&quot;]/label[1]</value>
      <webElementGuid>d79a7836-1492-49b7-aec7-34228a2031ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/VisorGeneralReporteEntrada/iframe_Mis Cesantas_SPW7D451709D4B45813735F_3b68a4</value>
      <webElementGuid>df2683ff-8579-45e8-ae87-498885deda6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupEntradaReporteVisor_form:dialogPopupEntradaReporte_content']/div/label</value>
      <webElementGuid>09cc771b-f0f0-4aa3-bbe6-c682440955f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontró registros'])[1]/following::label[1]</value>
      <webElementGuid>320eecb8-9185-44ba-ba7f-472245faab1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visor General Reporte'])[1]/following::label[1]</value>
      <webElementGuid>e22333a8-db84-4408-b2fa-dac0344a9fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::label[1]</value>
      <webElementGuid>3116dcef-bed3-418a-be1f-f589bcd2cf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::label[1]</value>
      <webElementGuid>bb3b74e7-2d8e-4afb-860e-013da9b90f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>a8ba788b-0583-4581-9764-ac86c302f705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '��entradas!!' or . = '��entradas!!')]</value>
      <webElementGuid>0a2f76ec-95cd-46ba-8faa-1ca38676bcbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
