<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_entradas</name>
   <tag></tag>
   <elementGuidId>3b70cce1-9905-4c1a-b936-a8ee87b33a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/div/form[1]/div/table[2]/tbody/tr[2]/td/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.us-head-popup.us-popup-img > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>88327aab-f35f-4306-8b44-b44d25f7ef87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>��entradas!!</value>
      <webElementGuid>326a606f-bf3d-47d1-8f52-012f9b4df980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupEntradaReporteVisor_form:dialogPopupEntradaReporte_content&quot;)/div[@class=&quot;us-head-popup us-popup-img&quot;]/label[1]</value>
      <webElementGuid>478e0df7-fb63-445c-9f00-e946f045e36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/VisorGeneralReporteEntrada/iframe_Mis Cesantas_SPW7D451709D4B45813735F_3b68a4</value>
      <webElementGuid>0b93ad53-a1fc-4ea2-a740-daad1aa91e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupEntradaReporteVisor_form:dialogPopupEntradaReporte_content']/div/label</value>
      <webElementGuid>ae922c59-4eb8-40e6-8c38-9e2063528f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontró registros'])[1]/following::label[1]</value>
      <webElementGuid>ee440704-7ae5-4a95-988e-0ef2b8c11026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visor General Reporte'])[1]/following::label[1]</value>
      <webElementGuid>09ca6610-f669-4aa7-aeaa-d68031ad1f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::label[1]</value>
      <webElementGuid>d9c16fa7-3139-446c-a73c-0bbe27aa12ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::label[1]</value>
      <webElementGuid>486e5263-de76-4804-b084-49e8f63d0d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>b56bc3d2-9faa-4189-aa3a-0eded176a3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '��entradas!!' or . = '��entradas!!')]</value>
      <webElementGuid>0798e56b-8774-4bbd-ac39-10a1d142fcbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
