<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aprendiz Sena Productiva_btn-hoja us-i_82001a</name>
   <tag></tag>
   <elementGuidId>0998619d-88b8-41bd-8b84-92a883cdf8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.btn-hoja.us-icon-card-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b67ad93d-40d1-42f7-a728-b80f3f05c796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-hoja us-icon-card-img</value>
      <webElementGuid>b8da965d-2397-4d1f-9438-2ff7b41c4c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contratosEmpleado:j_idt46:0:j_idt64&quot;)/span[@class=&quot;btn-hoja us-icon-card-img&quot;]</value>
      <webElementGuid>d982b0ae-73b8-4cc5-839b-4fcf7fd0da63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/ServicioMisIncapacidades/ConsultarIncapacidadesSubalternos/iframe_Mis Cesantas_7F07D451709D4B45813735F_dab634</value>
      <webElementGuid>eb3cf651-3469-4eb5-8fa5-13abca6aedd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='contratosEmpleado:j_idt46:0:j_idt64']/span</value>
      <webElementGuid>39a888c2-d8cc-488c-b7f1-9cdce687a052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>c6d30a94-09d2-47ff-93db-374388750f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
