<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aprendiz Sena Productiva_btn-hoja us-i_82001a</name>
   <tag></tag>
   <elementGuidId>0402bddb-cdcd-45da-8cdc-aaf31be13be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/div/div[3]/div/form/table/tbody/tr/td/table/tbody/tr[1]/td/table/tbody/tr/td/div/div[3]/div/div[3]/div[2]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn-hoja.us-icon-card-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c45318f7-54a4-4d84-9e14-43c0c695033a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-hoja us-icon-card-img</value>
      <webElementGuid>522644ff-8a4c-4dfa-b709-24357cb1c64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contratosEmpleado:j_idt46:0:j_idt64&quot;)/span[@class=&quot;btn-hoja us-icon-card-img&quot;]</value>
      <webElementGuid>c07820e0-94fa-4b6b-8147-a284641e9869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/ConsultarDescripcionCargoSubalterno/iframe_Mis Cesantas_descripcionCargoSubAlte_3904b7 - Copy</value>
      <webElementGuid>e5bef283-aa6d-488b-88e8-003c854400ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='contratosEmpleado:j_idt46:0:j_idt64']/span</value>
      <webElementGuid>c4c21b31-7223-4524-afb5-69a8af9c41f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>1a80bbbd-cfb7-49b2-913b-8ed9b9cda1b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
