<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aprendiz Sena Productiva_btn-hoja us-i_82001a</name>
   <tag></tag>
   <elementGuidId>0402bddb-cdcd-45da-8cdc-aaf31be13be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/div/div[3]/div/form/table/tbody/tr/td/table/tbody/tr[1]/td/table/tbody/tr/td/div/div[3]/div/div[3]/div[2]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn-hoja.us-icon-card-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f4a0b83c-64a7-4e23-821e-639abdf50532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-hoja us-icon-card-img</value>
      <webElementGuid>0e330c29-9017-45ca-837b-e2918807c0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contratosEmpleado:j_idt46:0:j_idt64&quot;)/span[@class=&quot;btn-hoja us-icon-card-img&quot;]</value>
      <webElementGuid>4971938a-0326-462b-a37c-786fcc784336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/ConsultarDescripcionCargoSubalterno/iframe_Mis Cesantas_descripcionCargoSubAlte_3904b7</value>
      <webElementGuid>5e7bc60c-a2bb-4264-a679-8eed7e28e50c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='contratosEmpleado:j_idt46:0:j_idt64']/span</value>
      <webElementGuid>04e4fca1-4280-4b72-a42d-cda290250f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>03ab1a93-dc7d-4058-884f-f4030aa626b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
