<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identificacion Evaluado_listadoHerram_058119</name>
   <tag></tag>
   <elementGuidId>03dace87-aa57-44f6-a79b-f5898461d840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98842f70-e883-4c3b-9be5-e3d08f349427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listadoHerramienta:j_idt90</value>
      <webElementGuid>faed8bb0-df7a-4b70-963d-7571c0c95f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listadoHerramienta:j_idt90</value>
      <webElementGuid>16ec3bc1-6cba-450d-8d5f-2e9f6180c2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b5ac8e4-2293-4c4c-ab6e-f0283687fc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all valor_campo ui-state-hover ui-state-focus</value>
      <webElementGuid>e9e31e49-8430-4f51-b166-bb525a278877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>38684142-f9f7-43d5-9df6-bfe9900b94b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;listadoHerramienta:j_idt90&quot;,e:&quot;valueChange&quot;,f:&quot;listadoHerramienta&quot;,p:&quot;listadoHerramienta:j_idt90&quot;,u:&quot;listadoHerramienta&quot;});</value>
      <webElementGuid>464a104c-938f-4512-936d-5907c49d7992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5c0656fb-f135-4541-8477-752ee3706ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7023e64b-0260-47b3-8443-2dd0141d04b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a27b6ce-e1ee-474a-bf9e-c465b6d8971d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listadoHerramienta:j_idt90&quot;)</value>
      <webElementGuid>f28d263e-965e-43ce-8ed0-bcdcaf1ae59e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='listadoHerramienta:j_idt90']</value>
      <webElementGuid>aaa21a30-cc53-4431-a4f6-c714debc5e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listadoHerramienta:panelFiltro_content']/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>e6e25199-2209-4eaa-99b0-2461b3bb99cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>d1e3c050-2528-4c61-ada4-2394f8dff5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'listadoHerramienta:j_idt90' and @name = 'listadoHerramienta:j_idt90' and @type = 'text']</value>
      <webElementGuid>03fb7732-b54a-4340-b2ad-b5a0f579c7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
