<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aplicada</name>
   <tag></tag>
   <elementGuidId>03dfa172-cf7a-42f0-8202-df19082883e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/div/div
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-cell-editor-output</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38baa325-993a-44d4-a9dd-5fe0f535573f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-cell-editor-output</value>
      <webElementGuid>6c442e54-7b63-4390-8938-632ea36123d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aplicada</value>
      <webElementGuid>8df12b01-c9c4-4fe7-b127-0e662c3807ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formEventoEvaluacion:panel_evento:tablaEvaluacion:0:j_idt743&quot;)/div[@class=&quot;ui-cell-editor-output&quot;]</value>
      <webElementGuid>c31bd51a-c0cf-4f6c-84ca-b0300540cfc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formEventoEvaluacion:panel_evento:tablaEvaluacion:0:j_idt743']/div</value>
      <webElementGuid>71ff4043-532a-4946-a761-bdf0bbd5bc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluación Capacitación'])[2]/following::div[2]</value>
      <webElementGuid>d102ce6d-f9f7-4617-bd27-d86767935bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Programa'])[1]/preceding::div[5]</value>
      <webElementGuid>0d8c1914-d392-4677-a401-af67e39a44e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Evento'])[1]/preceding::div[6]</value>
      <webElementGuid>55d2e418-d983-4572-8012-aceda0d90561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div</value>
      <webElementGuid>53519317-deff-4e0a-af12-008c836aaba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Aplicada' or . = 'Aplicada')]</value>
      <webElementGuid>2cab8bba-3209-4bb8-9a15-a6dc06ad93bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
