<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantidad_requerimientoPersonalPM_form_8bc9ff</name>
   <tag></tag>
   <elementGuidId>4330a369-b7f8-4314-8f63-5a9b3537e2d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='requerimientoPersonalPM_form:cantidad']
//*[@id=&quot;requerimientoPersonalPM_form:cantidad&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46650c05-40ac-4f6a-a3aa-67658522e93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requerimientoPersonalPM_form:cantidad</value>
      <webElementGuid>ae5f5abc-f9ab-49bb-8628-cef6d96795e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea0c8b3b-1349-4f53-8f77-4304f3e62a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requerimientoPersonalPM_form:cantidad</value>
      <webElementGuid>bddfaec8-1592-49c2-b6c4-5f962f55eb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4a70028d-6981-4f16-905c-d7b7d94bc7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>71ffdc3b-0377-4444-be5c-d454716edd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>24839da1-62f0-49ca-978c-dbe592cc343a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requerimientoPersonalPM_form:cantidad&quot;)</value>
      <webElementGuid>7e834888-4cdc-4e7c-af7e-bf8605d00f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/RequerimientoCargo/RequerimientoPuesto/iframe_Puesto de trabajo_7F07D451F09D4B3581_e1732d</value>
      <webElementGuid>ac3c93be-72e3-4a00-bf8e-884f3b19a34c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requerimientoPersonalPM_form:cantidad']</value>
      <webElementGuid>5174fc19-c3d6-4dc0-82ce-15a5a6fc6d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='requerimientoPersonalPM_form']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td[2]/div/table[2]/tbody/tr[4]/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>e3d6f755-2179-4da5-963b-6e95e45a48f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>a874f551-2292-4bda-a13d-ef391eee2ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'requerimientoPersonalPM_form:cantidad' and @type = 'text' and @name = 'requerimientoPersonalPM_form:cantidad']</value>
      <webElementGuid>31df1be5-98e4-417e-bf32-e4bfad16b1cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
