<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ha finalizado el proceso</name>
   <tag></tag>
   <elementGuidId>f97cbc19-9c62-40de-b0c1-3bee432bbabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-messages-info-detail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14c9b308-0dde-4e0b-89b6-0149876c98db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-messages-info-detail</value>
      <webElementGuid>0472acb8-b7b6-40ba-b501-115233dbb6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ha finalizado el proceso.</value>
      <webElementGuid>a1ab4514-3e67-466e-a8ef-2317b7580e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt463&quot;)/div[@class=&quot;ui-messages-info ui-corner-all&quot;]/ul[1]/li[1]/span[@class=&quot;ui-messages-info-detail&quot;]</value>
      <webElementGuid>eae44ce8-fd8f-4980-a17f-097aaaad7fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/RequerimientoCargo/RequerimientoPuesto/iframe_Puesto de trabajo_7F07D451F09D4B3581_e1732d</value>
      <webElementGuid>0ac17443-02b2-4c20-a783-0d793629aac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt463']/div/ul/li/span[2]</value>
      <webElementGuid>8f90fc3e-7e4b-4389-961e-0f80d11668d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFO:'])[1]/following::span[1]</value>
      <webElementGuid>73327b7e-df8d-4e52-986b-cad0f4ef0977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[2]/following::span[4]</value>
      <webElementGuid>b388ef7d-ed1c-4ccd-bebb-b32b0fe98754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[6]</value>
      <webElementGuid>75d45ca4-2261-48b3-aa82-45b4417c9522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::span[7]</value>
      <webElementGuid>b7db2979-8fee-4b23-9a9b-f4c6a8c8e325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ha finalizado el proceso.']/parent::*</value>
      <webElementGuid>0e427ee5-9011-46f3-bbfb-92e95222bcf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span[2]</value>
      <webElementGuid>5e48155a-0073-4ede-931f-083a5b413616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ha finalizado el proceso.' or . = 'Ha finalizado el proceso.')]</value>
      <webElementGuid>af58fd01-8e87-44bf-bf01-d4841ca67dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
