<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione --SolicitanteMarta Por_bc0c62</name>
   <tag></tag>
   <elementGuidId>9e93c431-2511-4312-bec8-f7c9a51a0d14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='formListadoEventos:pIMomentoEvento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0d2118a0-1008-4130-b085-f82aed39b115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formListadoEventos:pariente</value>
      <webElementGuid>de87495e-dfa5-4207-a880-51a3251fd6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formListadoEventos:pariente</value>
      <webElementGuid>3cbf70c9-7e40-4117-9318-b5b0892dea1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>12b34315-2de4-4275-91fb-05777963d162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b239de59-538a-48aa-ab97-a1d9f2e307f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;change&quot;,f:&quot;formListadoEventos&quot;,p:&quot;formListadoEventos&quot;,u:&quot;areaAplicacion&quot;});</value>
      <webElementGuid>1c26d161-f745-47fb-8d1b-2871587dbc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	-- Seleccione --
	Solicitante
	Marta Portal Noborrar
</value>
      <webElementGuid>cf9bd4e9-6ae0-4af3-8191-be09f6b4be2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formListadoEventos:pariente&quot;)</value>
      <webElementGuid>4d2ec812-d6f7-4f71-8b12-45e7eaf226c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/InscripcionEventoBienestar/iframe_Mis eventos_7F07D451F09D4B35813735F5_55247e</value>
      <webElementGuid>383a1a0e-4e8c-4278-9a08-83395c06b3bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formListadoEventos:pariente']</value>
      <webElementGuid>28a4a179-f1e4-492b-b8c7-64cfb23f7cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formListadoEventos:j_idt102_content']/div[2]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>f417499d-4453-4f33-896a-cd7b8af4e479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pariente *'])[1]/following::select[1]</value>
      <webElementGuid>d09779f9-2682-4653-a8ce-0cf310de4fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inscripción'])[1]/following::select[1]</value>
      <webElementGuid>2cae13a7-8232-4e3e-b198-7b64c8072f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formListadoEventos:pariente', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>fed1e57f-ca94-4cb2-9a6d-022f867f9d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::select[1]</value>
      <webElementGuid>2434b7e2-d538-4924-a61f-22d4364c24bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/select</value>
      <webElementGuid>d78423db-bf9d-4c16-851b-3327a7fc1329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'formListadoEventos:pariente' and @name = 'formListadoEventos:pariente' and (text() = '	-- Seleccione --
	Solicitante
	Marta Portal Noborrar
' or . = '	-- Seleccione --
	Solicitante
	Marta Portal Noborrar
')]</value>
      <webElementGuid>58dcb1ef-2bda-4880-bb0c-cdd2d5c5d811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
