<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione --SolicitanteMartaPariente</name>
   <tag></tag>
   <elementGuidId>ff1fff4c-b81d-4715-9877-79065cabfcd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='formListadoEventos:pariente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8cd92a6e-1f8b-481f-89d5-c3456a2d8c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formListadoEventos:pariente</value>
      <webElementGuid>0818af0b-ae95-49fe-8908-ee1fe60952a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formListadoEventos:pariente</value>
      <webElementGuid>4902a927-767d-44a1-92c2-69299a218872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>f82aa17a-759f-4b96-a7a4-a2526fcbf495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>63fd8f64-79d9-4101-a71f-57be25a4266e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;change&quot;,f:&quot;formListadoEventos&quot;,p:&quot;formListadoEventos&quot;,u:&quot;areaAplicacion&quot;});</value>
      <webElementGuid>b03cb567-22e4-4bd2-a8e5-37fbd2c75de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	-- Seleccione --
	Solicitante
	Marta Portal Noborrar
</value>
      <webElementGuid>b66661fd-8a46-4a02-b6a1-259e932c2cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formListadoEventos:pariente&quot;)</value>
      <webElementGuid>80f6a3ed-509a-4759-99ae-e3b0eb61941c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/InscripcionEventoBienestar/iframe_Mis eventos_7F07D451F09D4B35813735F5_55247e</value>
      <webElementGuid>0f7b9129-a011-47d7-ad0c-c0e43087fb8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formListadoEventos:pariente']</value>
      <webElementGuid>3e2d4349-300b-490b-9a3c-02d6c1f6861e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formListadoEventos:j_idt102_content']/div[2]/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>f75dc659-7c59-4768-bb62-47000c0878b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pariente *'])[1]/following::select[1]</value>
      <webElementGuid>99d6cc4c-e1e4-40df-a2a2-85d5251c2b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inscripción'])[1]/following::select[1]</value>
      <webElementGuid>f484eb96-fb26-4577-b9c1-13502dd1ca8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formListadoEventos:pariente', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>c153b152-ea0e-4bfa-9acc-25813cac4abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::select[1]</value>
      <webElementGuid>d7e27d51-b7a3-4fc2-a36c-7fd8045bde65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/select</value>
      <webElementGuid>0f95c85c-8ace-4756-aefd-3f96ff288438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'formListadoEventos:pariente' and @name = 'formListadoEventos:pariente' and (text() = '	-- Seleccione --
	Solicitante
	Marta Portal Noborrar
' or . = '	-- Seleccione --
	Solicitante
	Marta Portal Noborrar
')]</value>
      <webElementGuid>91a973df-d099-43c1-8d63-3d2c03686a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
