<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__hojaVidanombresTexto</name>
   <tag></tag>
   <elementGuidId>1fd526cb-ba92-4891-83f1-752c8996227e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11a17f69-37c3-4eb5-9ef4-9fe51cc8eae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hojaVida:seccion:j_idt119:1:idTexto</value>
      <webElementGuid>0ffc3c50-0f32-40df-9ba4-f007b827d88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>353726bc-14c9-4f0d-b69e-86d8db108e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hojaVida:seccion:j_idt119:1:idTexto</value>
      <webElementGuid>21754e06-398a-43cb-a473-cf8b650bd7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>EMPLEADO</value>
      <webElementGuid>be650e13-ce94-41c3-b0ca-f7157d13390c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar us-tx-primario </value>
      <webElementGuid>c82113ab-9316-4a9c-a702-6851f71c6ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6f4d33bf-a035-4283-9bf4-97b90d5490d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ac521d07-346e-4b37-9d2d-86029e859895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>17ff0c9a-7344-409e-9aeb-490aa7d47ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hojaVida:seccion:j_idt119:1:idTexto&quot;)</value>
      <webElementGuid>5a94742f-3af8-4822-86e0-4d45131ed220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/GenerarImprimirHojaVida/iframe_HojaVida</value>
      <webElementGuid>d7a875d4-f496-4a57-a9c0-0493b5b03e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hojaVida:seccion:j_idt119:1:idTexto']</value>
      <webElementGuid>73c0d04a-da0e-494b-b053-f83332a396c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hojaVida:seccion:j_idt115']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>61e1c3a4-591d-416e-bfa9-284578337c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>79b278c1-07be-46b0-b758-59ef2cc376b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hojaVida:seccion:j_idt119:1:idTexto' and @type = 'text' and @name = 'hojaVida:seccion:j_idt119:1:idTexto']</value>
      <webElementGuid>47d1d2ca-3929-4bcb-a10e-964637da5399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
