<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nacionalidad_j_idt744j_idt749</name>
   <tag></tag>
   <elementGuidId>3c1b7c64-2a3b-4847-a935-b7021bd5887b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1c217f5-c6d9-4116-8217-8c6c7c694ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt744:j_idt749</value>
      <webElementGuid>45c902ca-4a4e-4ce1-836b-aa16dd713eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_idt744:j_idt749</value>
      <webElementGuid>6d06099a-6bc3-46bf-a00a-db0aa7754cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1f68be7-876f-407e-b618-3725ac419d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ace_valor_campo_estandar ui-state-focus</value>
      <webElementGuid>3be8b11e-4f43-4eac-b124-261b5a4972ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e0477442-6111-449f-b44e-bce7e5a9e214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;j_idt744:j_idt749&quot;,e:&quot;valueChange&quot;,f:&quot;j_idt744&quot;,p:&quot;j_idt744:j_idt749&quot;,u:&quot;j_idt744&quot;});</value>
      <webElementGuid>2ee8f537-f634-40ca-982b-be00565aa677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b2ad890c-7d62-4834-85ca-ff35ec9346b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76b0f654-1b99-4d4d-9a33-c084b42047a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a54f22f5-41e5-4d7a-8024-bc9674062aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt744:j_idt749&quot;)</value>
      <webElementGuid>0839d3a3-30a9-4508-9ac3-5bd9840ec3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/DiligenciarHV/iframe_HojaVida</value>
      <webElementGuid>f8eabb26-1b97-4fc7-9b73-ddb927b3bd95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_idt744:j_idt749']</value>
      <webElementGuid>f6abb193-6411-4ce7-964f-1d77f474984f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt744:dialog_popUpNacionalidad_content']/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>bc68a232-90b4-454c-8ae5-2480e3e5273c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>b64bd5d1-7338-4f7a-ba00-5108ab936d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_idt744:j_idt749' and @name = 'j_idt744:j_idt749' and @type = 'text']</value>
      <webElementGuid>90306dc6-d49f-4f54-87ab-620a3eef1781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
