<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eliminar</name>
   <tag></tag>
   <elementGuidId>7fdd7eb2-cf4c-4e33-b5a5-2cef52cf911c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Eliminar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95646f8b-565e-4aae-8361-44f7c103027c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_licenciaEmpleado:tabsLicencias:panelLicenciaHistorico:j_idt2701</value>
      <webElementGuid>648f9d3e-789b-46d8-b63c-b95af052902c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6b10f343-d823-425e-a03e-edc2bc03f017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-eliminar</value>
      <webElementGuid>201a2331-e1da-4f02-b49d-ddc3a5732f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_licenciaEmpleado:tabsLicencias:panelLicenciaHistorico:j_idt2701&quot;,f:&quot;form_licenciaEmpleado&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>c65a5f53-3940-46ec-ac48-b07df2407c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>1696cae0-d036-4572-8dee-6f63f0656c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_licenciaEmpleado:tabsLicencias:panelLicenciaHistorico:j_idt2701&quot;)</value>
      <webElementGuid>01225aee-7632-4ca5-8e79-b52adebf19e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_licenciaEmpleado:tabsLicencias:panelLicenciaHistorico:j_idt2701']</value>
      <webElementGuid>484443fb-e97d-4ec7-922c-a59a919dab20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_licenciaEmpleado:tabsLicencias:panelLicenciaHistorico:j_idt2579']/table[4]/tbody/tr/td/a[2]</value>
      <webElementGuid>28055e69-2bcf-43fa-9884-8083b6e2a90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eliminar')]</value>
      <webElementGuid>dec653a4-f8bf-4ede-9d7c-2558b293d0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha 1'])[1]/following::a[2]</value>
      <webElementGuid>975b4f0c-1130-48d7-9fd6-51e32352ac93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PruebaAutoK'])[1]/following::a[2]</value>
      <webElementGuid>4b25a8aa-d533-4634-8286-b9027810a00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuperar Incapacidad'])[1]/preceding::a[3]</value>
      <webElementGuid>08de5db2-e61b-4fc5-9609-59b127fb1a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[1]/preceding::a[3]</value>
      <webElementGuid>bcc358cf-48fa-4a04-ae4f-017b40ae0131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eliminar']/parent::*</value>
      <webElementGuid>bffe904f-594d-46f6-b1e1-de26129003be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[116]</value>
      <webElementGuid>24f6fb29-2998-4589-a645-12e06c0fb476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>e863f2d8-2122-4d4b-a694-84ac16cedce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_licenciaEmpleado:tabsLicencias:panelLicenciaHistorico:j_idt2701' and @href = '#' and (text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>f4455ba0-e7e9-41c5-b85a-c162d85645dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
