<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha esperada para el cubrimiento de_4c2800</name>
   <tag></tag>
   <elementGuidId>8a370d87-5fda-4009-ad74-5f5e56dd7aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[2]/span/input
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>375ddd70-1bce-4640-99de-d8a88bc2350d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requerimientoPersonalPM_form:j_idt706:0:tablaCamHijo:1:fecha_input</value>
      <webElementGuid>1b82ef2a-b91e-4911-b860-5855f836dd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requerimientoPersonalPM_form:j_idt706:0:tablaCamHijo:1:fecha_input</value>
      <webElementGuid>111e3704-ad37-4ff0-8d53-7423ad2ee47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e079add3-0280-455a-b175-70da13c31aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker ui-state-hover ui-state-focus</value>
      <webElementGuid>fe6ab90d-637d-47d0-82fe-80561cf5ff1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0f437510-0fc9-4883-8422-ff90f9244595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e36de14f-8cd6-455d-bdbc-ca5b474af227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d087e8f6-a2a6-4b66-a3df-cbcfa38f47d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requerimientoPersonalPM_form:j_idt706:0:tablaCamHijo:1:fecha_input&quot;)</value>
      <webElementGuid>da49b64d-5dd3-4798-afc3-ffda0c65c9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/RequerimientoCargo/RequerimientoCargoNuevo/iframe_Nuevo cargo_7F07D451F09D4B35813735F5_66e4dc</value>
      <webElementGuid>7abe14a4-83cf-4bd6-9423-d6de9189196f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requerimientoPersonalPM_form:j_idt706:0:tablaCamHijo:1:fecha_input']</value>
      <webElementGuid>4a4532c1-695b-410a-a7fc-eda63627887f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='requerimientoPersonalPM_form:j_idt706:0:tablaCamHijo:1:fecha']/input</value>
      <webElementGuid>82f68208-6dad-4564-a2e3-9f4ddef03b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span/input</value>
      <webElementGuid>cff6545a-092c-4a9f-a0ae-94f55699a896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'requerimientoPersonalPM_form:j_idt706:0:tablaCamHijo:1:fecha_input' and @name = 'requerimientoPersonalPM_form:j_idt706:0:tablaCamHijo:1:fecha_input' and @type = 'text']</value>
      <webElementGuid>1a7c1397-e967-439b-ace0-4a2c1a5a86af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
