<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aplicar</name>
   <tag></tag>
   <elementGuidId>a2cdb9ac-6f91-43b5-8701-edefef90dc0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Aplicar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc53c6c6-55b7-43b1-b886-6c3aa8945fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupCambiarTipoHoja:j_idt941</value>
      <webElementGuid>17b535a1-d9ad-414f-96c9-fd1903457b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6f1671b9-34c4-4114-bb2d-3288a9ac8184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-acepto</value>
      <webElementGuid>b1baa61d-8094-4558-84b8-b6ec1aac4367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;popupCambiarTipoHoja:j_idt941&quot;,f:&quot;popupCambiarTipoHoja&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>da807add-386f-416a-8d7c-2ac9dd103dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aplicar</value>
      <webElementGuid>ae2bcc13-604e-4480-a9f2-5c44995b33f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupCambiarTipoHoja:j_idt941&quot;)</value>
      <webElementGuid>5141cb5a-6244-4f20-81ab-3ed591f0a77b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='popupCambiarTipoHoja:j_idt941']</value>
      <webElementGuid>ba636eb6-dfaa-4c66-ac11-4d50c23d4dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupCambiarTipoHoja:popupCambiarTipo_content']/div[2]/a</value>
      <webElementGuid>1f508e59-ee6d-4579-95bc-a3953940355e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Aplicar')]</value>
      <webElementGuid>67c333df-e4e1-443c-a2ed-db7b40a21740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione Tipo de Hoja'])[1]/following::a[1]</value>
      <webElementGuid>95208275-76c8-4c1f-ad2e-07bc0de5bc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>67b98513-4722-47e2-87d7-fa54f009cf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[1]</value>
      <webElementGuid>2b344f76-06e5-4ed4-9962-8511df38fd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aplicar']/parent::*</value>
      <webElementGuid>a452b0a8-48e9-4628-8b04-98500ff86410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[69]</value>
      <webElementGuid>fb37eb85-f82b-40ad-b452-36897abb582b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>7b06964a-62cd-45f8-b906-de30c893b1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'popupCambiarTipoHoja:j_idt941' and @href = '#' and (text() = 'Aplicar' or . = 'Aplicar')]</value>
      <webElementGuid>fde5354b-3abe-4673-8e6e-678ef6567a54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
