<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Candidato</name>
   <tag></tag>
   <elementGuidId>b78f20fa-f0e2-4589-a18a-70b4c3d8a965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Candidato']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a9f6003-3ace-4ad2-8ec6-b91052a4cecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt661:j_idt662:j_idt664:j_idt712_header</value>
      <webElementGuid>aff87cc5-49b9-42e3-9713-39de2b2d85bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-accordion-header ui-helper-reset ui-state-default ui-state-active ui-corner-top ui-tabs-outline</value>
      <webElementGuid>512b54b7-e9b8-4849-9ff6-324c60d431b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>609b87f0-c775-4435-b490-29083d469efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9a32bf8-781b-41cb-a9a0-30e518a3616e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a7e3bd1-9613-4996-b262-a1910bbc3e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51b5595d-1cec-4d08-be07-ac7a21530df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Candidato</value>
      <webElementGuid>919361cf-fd28-4b4b-b931-4fd37af320b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt661:j_idt662:j_idt664:j_idt712_header&quot;)</value>
      <webElementGuid>77c95d45-ca30-4e19-8ee7-c83f83ee8d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='j_idt661:j_idt662:j_idt664:j_idt712_header']</value>
      <webElementGuid>2239ea60-0f35-4033-8a00-a5615e3b4128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt661:j_idt662:j_idt664']/div[3]</value>
      <webElementGuid>b097b7a0-485a-47fb-ae90-ac38e919173f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceso'])[1]/following::div[2]</value>
      <webElementGuid>ce082f43-4d0f-4ebd-ba65-b9a4f44e4cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parámetros'])[2]/following::div[10]</value>
      <webElementGuid>0c114b25-9b38-4cb8-b071-ff3ae4d2939c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Citacion'])[1]/preceding::div[2]</value>
      <webElementGuid>e0eb407e-2091-4df5-b7f5-2b1996cc5b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes'])[1]/preceding::div[4]</value>
      <webElementGuid>9333673d-f01d-4ae2-8540-aa577eeedada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Candidato']/parent::*</value>
      <webElementGuid>234a3858-535c-47e1-a3d8-785249f73bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[3]</value>
      <webElementGuid>07485eea-e675-47cd-b7eb-bd9c66b7f575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'j_idt661:j_idt662:j_idt664:j_idt712_header' and (text() = 'Candidato' or . = 'Candidato')]</value>
      <webElementGuid>bbb18e68-06e6-4a40-a3a5-1857dff87a59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
