<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identificacin_listado_hojaVidaj_idt68</name>
   <tag></tag>
   <elementGuidId>b1b255c5-1a35-4dbc-b621-b0b9668c1df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[4]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be471085-b0ee-4d5c-bba5-4868f0a1b458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listado_hojaVida:j_idt68</value>
      <webElementGuid>be4bf727-f6ca-41d6-af2e-354069192724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3a001d5-1aab-48b7-be8b-069f4729ed47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listado_hojaVida:j_idt68</value>
      <webElementGuid>c236b137-2040-4db9-8180-12c4d75bedee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>6cb06375-18bd-4c68-858a-4734c615acca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>18be2f63-ae84-40e5-8adb-0ce31540eb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;change&quot;,f:&quot;listado_hojaVida&quot;,p:&quot;listado_hojaVida:j_idt68&quot;,u:&quot;listado_hojaVida:tablaHojaVida&quot;});</value>
      <webElementGuid>723177aa-fc9f-44de-8955-7e5742c9ff53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listado_hojaVida:j_idt68&quot;)</value>
      <webElementGuid>4e74427a-0009-49d2-936c-ada8b9bc2b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='listado_hojaVida:j_idt68']</value>
      <webElementGuid>d652bf3d-fdc2-4e50-accc-da410d7959a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listado_hojaVida:panelFiltro_content']/table/tbody/tr/td[4]/input</value>
      <webElementGuid>771c76b0-2c47-489f-ba36-847a9ffb5333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>72da04ea-39ba-4e0a-ae88-37bd6fd01d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'listado_hojaVida:j_idt68' and @type = 'text' and @name = 'listado_hojaVida:j_idt68']</value>
      <webElementGuid>aca2df0e-1bd9-456d-a3bd-4feef3284996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
