<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RRHH</name>
   <tag></tag>
   <elementGuidId>39ecad01-e68e-4882-972c-ad5f29c11794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/header/div[3]/div/div/div[2]/nav/div/div[2]/div/nav/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
