<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form_solicitudesEmpleadoj_idt1520tab_89c254</name>
   <tag></tag>
   <elementGuidId>c6540387-c235-46fa-9324-a5efe1cccfc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48fd1c30-1b74-4603-bf0c-708c7e4b70fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_solicitudesEmpleado:j_idt152:0:tablaCamHijo:1:fecha_input</value>
      <webElementGuid>f430f45b-5830-4a0d-8f88-ba288639f469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_solicitudesEmpleado:j_idt152:0:tablaCamHijo:1:fecha_input</value>
      <webElementGuid>88e80242-3266-4a7f-ac19-30478c237006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>855db6b4-ff05-4a76-820b-4f6c372a8b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker ui-state-hover ui-state-focus</value>
      <webElementGuid>815d4073-373d-4a5f-b167-8786ff4e452e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>9512e12f-2d89-4c69-9d94-19d4657f25b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2a529e16-bcd2-449c-9a16-e91c1040b404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>833744ac-80e3-4332-9e4c-b12bb7a8984e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_solicitudesEmpleado:j_idt152:0:tablaCamHijo:1:fecha_input&quot;)</value>
      <webElementGuid>c108d97d-b885-45fb-b6bd-01dad9f74666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/ServicioMisCensantias/SolicitarAutorizarCesantiasBPM/iframe_Mis Cesantas_FB1846019F574996BB0A814_6cece9</value>
      <webElementGuid>678f8821-9b19-4b7c-861d-9434069c0601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_solicitudesEmpleado:j_idt152:0:tablaCamHijo:1:fecha_input']</value>
      <webElementGuid>763659ae-0709-4afc-b885-fde54f9b16fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='form_solicitudesEmpleado:j_idt152:0:tablaCamHijo:1:fecha']/input</value>
      <webElementGuid>044e7cb5-cbd2-42f7-9ca3-927b5985b47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span/input</value>
      <webElementGuid>881811e7-e9b0-4c34-b573-304d6f8325c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_solicitudesEmpleado:j_idt152:0:tablaCamHijo:1:fecha_input' and @name = 'form_solicitudesEmpleado:j_idt152:0:tablaCamHijo:1:fecha_input' and @type = 'text']</value>
      <webElementGuid>55e559b5-48ce-45b3-bf0d-e439e7bdf6a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
