<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Actualizar</name>
   <tag></tag>
   <elementGuidId>089ae2d4-a285-4497-8ed9-3553cf88d291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.us-boton.btn-nuevo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Actualizar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jsf.util.chain(this,event,';convertirClaveUsuario(              \'form_cambioContrasenia:passwordNuevo\',              \'form_cambioContrasenia:passwordConfirma\',           \'form_cambioContrasenia:solicitudClave\',           \'form_cambioContrasenia:solicitudClaveConfirma\',           \'7c149581d8cfbecb32f0a02aacb7cd7d98a00c4805bb4385993c53d5dc1db3b864c672dc44dd541c2f667ced0268db299fcf\',           \'10001\');','mojarra.jsfcljs(document.getElementById(\'form_cambioContrasenia\'),{\'form_cambioContrasenia:j_idt30\':\'form_cambioContrasenia:j_idt30\'},\'\')');return false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-boton btn-nuevo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualizar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_cambioContrasenia&quot;)/table[3]/tbody[1]/tr[1]/td[1]/a[@class=&quot;us-boton btn-nuevo&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/RealizarCambioContraseña/iframe_Recuperar Clave Preguntas_7F07D45170_d61892</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;jsf.util.chain(this,event,';convertirClaveUsuario(              \'form_cambioContrasenia:passwordNuevo\',              \'form_cambioContrasenia:passwordConfirma\',           \'form_cambioContrasenia:solicitudClave\',           \'form_cambioContrasenia:solicitudClaveConfirma\',           \'7c149581d8cfbecb32f0a02aacb7cd7d98a00c4805bb4385993c53d5dc1db3b864c672dc44dd541c2f667ced0268db299fcf\',           \'10001\');','mojarra.jsfcljs(document.getElementById(\'form_cambioContrasenia\'),{\'form_cambioContrasenia:j_idt30\':\'form_cambioContrasenia:j_idt30\'},\'\')');return false&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_cambioContrasenia']/table[3]/tbody/tr/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Actualizar')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar Clave'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva Clave'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Actualizar']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Actualizar' or . = 'Actualizar')]</value>
   </webElementXpaths>
</WebElementEntity>
