<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ifmail</name>
   <tag></tag>
   <elementGuidId>121a1a9d-6419-45e5-a3de-a61acd0cfce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div/div/main/div[2]/div[3]/div/div[1]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>IFRAME</value>
      <webElementGuid>487caaaa-8908-470e-a7c2-e5118a54c186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657918290557</value>
      <webElementGuid>186bea88-3006-43bf-ae38-20027376ac88</webElementGuid>
   </webElementProperties>
</WebElementEntity>
