<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ifrm_component_C_2</name>
   <tag></tag>
   <elementGuidId>e39efa87-3643-479b-bc05-875292f91b3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ifrm_component_C_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>IFRAME</value>
      <webElementGuid>a60dad4e-1e69-4fd3-98e2-b47e23948a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657912129085</value>
      <webElementGuid>aecc1f58-5808-4c39-994e-d2a0a457fdf7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
