<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombres</name>
   <tag></tag>
   <elementGuidId>05e5e692-fcc6-43b0-a2c9-89d0a0d71cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//body/div[1]/div/div[2]/div/div[3]/form/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr/td/div/div/div/table/tbody/tr[1]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>9d51d4d5-6445-4cc9-a354-f24fd8f25e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1657921563395</value>
      <webElementGuid>6ac63255-e970-4a8a-9e21-60e8603604a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/InscripcionPortal/iframe_component_A_1</value>
      <webElementGuid>283d1a3e-4fd5-45e9-bb39-b57149be88aa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
