<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_institucion</name>
   <tag></tag>
   <elementGuidId>a4736e28-6194-4531-a763-8816a5a411ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div/div[2]/div/table[2]/tbody/tr/td/form/div/div[2]/div[2]/table/tbody/tr/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d4ad48b6-d3c4-4b77-bfae-bdd880317e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1658152978071</value>
      <webElementGuid>e3522933-2dcc-417e-ad31-38264246c5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/InscripcionPortal/iframe_ifrm_component_A_2</value>
      <webElementGuid>3873becd-abd6-48fe-81e0-d9fee4cc6b3a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
