<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Periodo Nomina_LiquidacionNominaj_idt68</name>
   <tag></tag>
   <elementGuidId>2249c036-43cf-46cc-a88f-d2a0c8e672bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LiquidacionNomina:j_idt68']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e21cf20-220c-4468-b62b-9c5359c3378b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiquidacionNomina:j_idt68</value>
      <webElementGuid>b74bacf0-aca1-417c-bbc6-8ddebf329fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ff2d47ad-a726-47b7-a1c3-2baceb8d06e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn_popupInformacion</value>
      <webElementGuid>5773d967-3312-49bf-a7e0-b7f34858581f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;LiquidacionNomina:j_idt68&quot;,f:&quot;LiquidacionNomina&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>a36067a7-e7aa-46f5-8987-8cc6fcb220dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiquidacionNomina:j_idt68&quot;)</value>
      <webElementGuid>1c017094-78fc-47e6-ba6a-a3439ccbb28c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LiquidacionNomina:j_idt68']</value>
      <webElementGuid>cb1397eb-e3cc-4beb-b46c-8e2508d9190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LiquidacionNomina']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>80c82f90-9006-4e8a-ae34-8d91f013e7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[80]</value>
      <webElementGuid>e5bddefe-bdac-4ef1-a9ec-2fcfe36b25de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>44937a49-58ba-4297-9131-2fae6b6bb9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'LiquidacionNomina:j_idt68' and @href = '#']</value>
      <webElementGuid>b8ea0490-1047-4756-b33e-bb58d7f277cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
