<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Publicar</name>
   <tag></tag>
   <elementGuidId>5ccd826b-084d-492b-a330-643bd1aeeaa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='formComprobantePop:j_idt2477']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09daa68e-d787-4464-aeef-6f58a1305fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formComprobantePop:j_idt2477</value>
      <webElementGuid>a4d5d213-46fb-4b6d-b0b9-ecf4c30a610f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c6c694ed-2cf8-42c6-8109-76a73f3b8084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-plantilla</value>
      <webElementGuid>58f55898-36a1-44ae-a9bd-1fb17c827980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery(this).addClass('ui-state-disabled');PrimeFaces.ab({s:&quot;formComprobantePop:j_idt2477&quot;,f:&quot;formComprobantePop&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>29081df4-0f0d-4948-955d-ac13ff6cebeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publicar</value>
      <webElementGuid>fb293077-0111-4b41-b635-c4a81e31f72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formComprobantePop:j_idt2477&quot;)</value>
      <webElementGuid>effda3bd-2d04-446b-a76d-a9453fd8dd22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formComprobantePop:j_idt2477']</value>
      <webElementGuid>5e0af47f-ed04-491e-8686-71b1bf1806a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formComprobantePop:j_idt2453_content']/div[2]/a</value>
      <webElementGuid>c961eed1-c184-4d9b-aa2f-7de63dea8cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Publicar')]</value>
      <webElementGuid>0548ee76-67a5-490f-bfb0-4b835ce0b052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba'])[1]/following::a[1]</value>
      <webElementGuid>0a3f6b39-a4a9-4f70-883e-5b7af13c4e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::a[1]</value>
      <webElementGuid>814606de-84ad-403d-82e2-3139c16f21a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formComprobantePop:j_idt2477', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>6a318497-404d-4a9c-843a-f4b6d5689f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[2]</value>
      <webElementGuid>610a5c50-fbff-453d-853c-1c5e1403cdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[110]</value>
      <webElementGuid>e4e1c9bf-beb4-4696-8d8b-4f158603f482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>09166d53-c464-4b39-900c-fd32c1379aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formComprobantePop:j_idt2477' and @href = '#' and (text() = 'Publicar' or . = 'Publicar')]</value>
      <webElementGuid>7b5a5c50-7301-409f-bd32-138b289ae38d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
