<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Publicar</name>
   <tag></tag>
   <elementGuidId>5ccd826b-084d-492b-a330-643bd1aeeaa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/table/tbody/tr[4]/td/table/tbody/tr/td/form/div/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6c5d689-1800-4f2e-9b16-eb3090b19261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formComprobantePop:j_idt2477</value>
      <webElementGuid>38b93caf-fd45-4eb4-8ac5-8bef116c527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3efb51b2-7c78-495b-ae3c-178cd0e68070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-plantilla</value>
      <webElementGuid>b6d6c12b-899a-4bc9-b429-d5b6a237d74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery(this).addClass('ui-state-disabled');PrimeFaces.ab({s:&quot;formComprobantePop:j_idt2477&quot;,f:&quot;formComprobantePop&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>e96f7c07-eadc-4c40-a182-4a82d1f73292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publicar</value>
      <webElementGuid>63fd2ca6-18a9-42b8-91e2-ff4e097a62f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formComprobantePop:j_idt2477&quot;)</value>
      <webElementGuid>4f7800a9-1ad6-43be-b60d-3e20049d8fd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='formComprobantePop:j_idt2477']</value>
      <webElementGuid>57a810be-15e8-48e5-89b0-d0e661e633e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formComprobantePop:j_idt2453_content']/div[2]/a</value>
      <webElementGuid>b3b1bdb2-577f-401d-bbaf-bc88e0ee9b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Publicar')]</value>
      <webElementGuid>bef2a559-8dde-4dd0-9803-266eeef559a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba'])[1]/following::a[1]</value>
      <webElementGuid>bc991f96-fb2c-4f3e-8254-dcc39382fd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::a[1]</value>
      <webElementGuid>8d7e3a97-deea-4a7a-a029-2a5e0410d3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formComprobantePop:j_idt2477', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>8be656a7-74ed-4acb-aba1-c7df0067b4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[2]</value>
      <webElementGuid>0b6629c5-b0e6-441f-a08c-5d94311f86e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[110]</value>
      <webElementGuid>2c7d129f-47e7-481f-a8a3-fd18500d2884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>7e1213f7-8c7b-4696-a65f-dc78213d002e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'formComprobantePop:j_idt2477' and @href = '#' and (text() = 'Publicar' or . = 'Publicar')]</value>
      <webElementGuid>aba991f3-895a-4b6e-844c-979f09c40a64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
