<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrato_LiquidacionNominaj_idt128</name>
   <tag></tag>
   <elementGuidId>280e4f88-1740-44e7-9eb3-9854f050c025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LiquidacionNomina:j_idt128']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5adac69-44e3-434f-b2d6-051758d3234e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiquidacionNomina:j_idt128</value>
      <webElementGuid>486c3344-6d87-4a9f-b9ff-d297f328d531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e4f3ef8-6712-439c-b558-7b4717ce0270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LiquidacionNomina:j_idt128</value>
      <webElementGuid>8ec65063-2e5b-4823-b89f-abc754e4deba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>2fe5faa7-6628-4124-8749-ecff0ebd40a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>28349a96-7d06-4585-8bd3-cd61dd05f107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>751b0bb6-a686-464c-b065-1bb2aec39008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;LiquidacionNomina&quot;,p:&quot;LiquidacionNomina:j_idt128&quot;,u:&quot;LiquidacionNomina:tabla_ln&quot;});</value>
      <webElementGuid>61e951ee-5544-4f02-83ef-ed3d203fdbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiquidacionNomina:j_idt128&quot;)</value>
      <webElementGuid>e23ef3c5-ac56-4077-97fc-c0fddd1efc59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LiquidacionNomina:j_idt128']</value>
      <webElementGuid>d28b03f4-e7fa-4394-8ac9-12f3df978cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LiquidacionNomina:j_idt120_content']/table/tbody/tr/td[4]/input</value>
      <webElementGuid>70f3f76d-dbd6-468e-8751-580edf52ce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[4]/input</value>
      <webElementGuid>0387e1b6-d45d-45bd-b092-8815e70b93fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LiquidacionNomina:j_idt128' and @type = 'text' and @name = 'LiquidacionNomina:j_idt128']</value>
      <webElementGuid>c26bb3ea-59cb-41d3-b457-b4d4cf79d198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
