<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Publicar</name>
   <tag></tag>
   <elementGuidId>da7f9cf0-c44f-4b6d-8442-87779975d82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='formComprobantePop:tipo']/tbody/tr[2]/td/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>924a4504-6bee-47ea-bf51-c2e98c3fb75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>formComprobantePop:tipo:1</value>
      <webElementGuid>1254e680-f4ec-4d71-a542-7097c3ce1e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Publicar</value>
      <webElementGuid>9e6b7305-94ad-4c87-bffb-a6dcffe2b7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formComprobantePop:tipo&quot;)/tbody[1]/tr[2]/td[1]/label[1]</value>
      <webElementGuid>0b9e8fc9-b083-4c5c-a279-041f6645c53e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='formComprobantePop:tipo']/tbody/tr[2]/td/label</value>
      <webElementGuid>eb5fb0da-d869-4a55-8432-f1908337d567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviar Correo'])[1]/following::label[1]</value>
      <webElementGuid>3721033a-9c47-41ce-871e-20727615b129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobante De Pago'])[1]/following::label[2]</value>
      <webElementGuid>d73b998a-0419-43ed-b1b6-342411c981e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos'])[1]/preceding::label[1]</value>
      <webElementGuid>6a180950-1a69-4e0c-9403-d70aba205967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formComprobantePop:tipo', '&quot;', ')/tbody[1]/tr[2]/td[1]/label[1]')])[1]/preceding::label[2]</value>
      <webElementGuid>d29c6f18-e520-496b-a3b8-059303756978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publicar']/parent::*</value>
      <webElementGuid>6ae1fc31-a86c-4a38-a59d-d5164bd57330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label</value>
      <webElementGuid>1514f5e8-ff00-4ffc-b520-1ffa804968fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Publicar' or . = ' Publicar')]</value>
      <webElementGuid>33db78ed-da21-47ab-9758-727595fc04cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
