<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Publicar</name>
   <tag></tag>
   <elementGuidId>da7f9cf0-c44f-4b6d-8442-87779975d82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='formComprobantePop:tipo']/tbody/tr[3]/td/label
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3be68fba-5de6-49cd-ae75-7ed4c83b98e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>formComprobantePop:tipo:1</value>
      <webElementGuid>48b8acbf-d783-4448-b6bd-3a3938b034bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Publicar</value>
      <webElementGuid>edeb15ff-c0a9-4b60-b6ee-5304839f43ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formComprobantePop:tipo&quot;)/tbody[1]/tr[2]/td[1]/label[1]</value>
      <webElementGuid>62d7f240-07d7-4041-abb1-a126c3b4a2dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='formComprobantePop:tipo']/tbody/tr[2]/td/label</value>
      <webElementGuid>01b8d96b-bdd4-44af-91fa-2a172920caf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviar Correo'])[1]/following::label[1]</value>
      <webElementGuid>18e6ab87-f78f-4b7a-b380-e0e2226675f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobante De Pago'])[1]/following::label[2]</value>
      <webElementGuid>ecc46ce0-5f26-4101-af18-02c0b9f1a24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos'])[1]/preceding::label[1]</value>
      <webElementGuid>b67085ca-6452-455c-b1cb-ff975eb30ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formComprobantePop:tipo', '&quot;', ')/tbody[1]/tr[2]/td[1]/label[1]')])[1]/preceding::label[2]</value>
      <webElementGuid>7da40a50-405d-42a1-8948-833732be5428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publicar']/parent::*</value>
      <webElementGuid>7b27884e-5dd7-40d4-84d2-dc884be4319a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label</value>
      <webElementGuid>e409617a-2654-4fc3-ac7a-db3da1d9ed21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Publicar' or . = ' Publicar')]</value>
      <webElementGuid>e86ac2f7-07fa-46bf-833f-75cfe8c92c9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
