<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione --Comprobante de Nomina</name>
   <tag></tag>
   <elementGuidId>ea40841e-c02f-4736-861f-a07c8c83979b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='formComprobantePop:j_idt2461']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba2856d8-fce5-4b65-ac14-eb215d9a4161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formComprobantePop:j_idt2461</value>
      <webElementGuid>f6c418a1-7be8-4df3-bb44-a1a06366fa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formComprobantePop:j_idt2461</value>
      <webElementGuid>d2792a8d-d800-4282-a97c-995a43d4137d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>6117d730-b06f-4e10-99bc-09a0da7465ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc658d5e-53a5-4e98-9dd4-66cb0eb9a369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;formComprobantePop&quot;,p:&quot;formComprobantePop:j_idt2461&quot;,u:&quot;formComprobantePop&quot;});</value>
      <webElementGuid>7e024b1b-3da1-433c-841a-bb2f8cd4b421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	-- Seleccione --
	Comprobante de Nomina
</value>
      <webElementGuid>1372b892-d0e7-49dc-87b2-67e4c2f34674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formComprobantePop:j_idt2461&quot;)</value>
      <webElementGuid>8f8560dc-722c-4928-b45d-e207717aaf0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formComprobantePop:j_idt2461']</value>
      <webElementGuid>70b721b4-8cde-468f-9d2c-9a7b6bb87881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formComprobantePop:j_idt2453_content']/div[2]/table[2]/tbody/tr/td[2]/select</value>
      <webElementGuid>04034287-672f-4592-a175-1c20df7e8f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo *'])[1]/following::select[1]</value>
      <webElementGuid>424d5145-5219-4e1f-827b-ad62d43e1aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos'])[1]/following::select[1]</value>
      <webElementGuid>aa1f2970-163f-4017-bf28-2d8528104510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/preceding::select[1]</value>
      <webElementGuid>d94736b8-1cc4-4c36-96e5-5657359a2efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba'])[1]/preceding::select[1]</value>
      <webElementGuid>4eaacfdc-a8b4-4919-bb46-cac56c920e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/select</value>
      <webElementGuid>dcf373de-cfd4-4b7c-a285-b467648eea99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'formComprobantePop:j_idt2461' and @name = 'formComprobantePop:j_idt2461' and (text() = '	-- Seleccione --
	Comprobante de Nomina
' or . = '	-- Seleccione --
	Comprobante de Nomina
')]</value>
      <webElementGuid>41862f71-4bd6-49e7-9d47-b98c9a70e783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
