<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione --Comprobante de Nomina</name>
   <tag></tag>
   <elementGuidId>ea40841e-c02f-4736-861f-a07c8c83979b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/table/tbody/tr[4]/td/table/tbody/tr/td/form/div/div[2]/div[2]/table/tbody/tr[2]/td[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1293fc41-05c2-4d1f-a156-747dac2e7acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formComprobantePop:j_idt2461</value>
      <webElementGuid>f3097e8f-b7c2-46eb-af1f-9f2b3c870c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formComprobantePop:j_idt2461</value>
      <webElementGuid>6b87f458-4e95-47ec-888a-46ee189e0d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>f0774c23-cbf7-489c-93cb-cd2f4d7df713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6acc3e64-5b13-4ef3-901b-bf6fffeeecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;formComprobantePop&quot;,p:&quot;formComprobantePop:j_idt2461&quot;,u:&quot;formComprobantePop&quot;});</value>
      <webElementGuid>d52e8e39-ae1a-45b8-9b07-9ef5c5571735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	-- Seleccione --
	Comprobante de Nomina
</value>
      <webElementGuid>7c5baa71-7330-431c-9af3-2d7b3ecad6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formComprobantePop:j_idt2461&quot;)</value>
      <webElementGuid>de36d3a7-9d67-4034-9df5-a31bc87d7ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formComprobantePop:j_idt2461']</value>
      <webElementGuid>f2303226-eb43-486a-8c93-748a48435b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formComprobantePop:j_idt2453_content']/div[2]/table[2]/tbody/tr/td[2]/select</value>
      <webElementGuid>854d28af-76e6-4f36-9c73-8b791f76e257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo *'])[1]/following::select[1]</value>
      <webElementGuid>22fe9e4b-4e01-424f-ab34-042f32c73428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos'])[1]/following::select[1]</value>
      <webElementGuid>ff532e4e-423b-49fa-8198-2d598472c8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/preceding::select[1]</value>
      <webElementGuid>221dd746-d49b-4379-8881-6423e8bb493e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba'])[1]/preceding::select[1]</value>
      <webElementGuid>32029056-4a67-48c8-a543-87086b400b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/select</value>
      <webElementGuid>dbe47aec-5499-4d7e-be3f-93e0efa2c885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'formComprobantePop:j_idt2461' and @name = 'formComprobantePop:j_idt2461' and (text() = '	-- Seleccione --
	Comprobante de Nomina
' or . = '	-- Seleccione --
	Comprobante de Nomina
')]</value>
      <webElementGuid>98741d28-5e5e-4738-ac8a-5e7b3f6f716e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
