<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Liquidacion Nom</name>
   <tag></tag>
   <elementGuidId>5e5fe340-c7cd-4be3-a2f3-1f517b693ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/span/ul/li/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-autocomplete-query</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4535a96d-3cf2-4f48-aa8a-edda392b5521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-query</value>
      <webElementGuid>10f8f45e-dd0c-459e-afa2-e0d29e6d9ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liquidacion Nom</value>
      <webElementGuid>597fea66-12b8-487c-b920-8a4f8028659e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_template:j_idt24_panel&quot;)/ul[@class=&quot;ui-autocomplete-items ui-autocomplete-list ui-widget-content ui-widget ui-corner-all ui-helper-reset&quot;]/li[@class=&quot;ui-autocomplete-item ui-autocomplete-list-item ui-corner-all ui-state-highlight&quot;]/span[@class=&quot;ui-autocomplete-query&quot;]</value>
      <webElementGuid>a0d09cfe-de2f-4e45-a8a6-7cc082d7bcbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='form_template:j_idt24_panel']/ul/li/span</value>
      <webElementGuid>d06fd06b-44a4-40e4-b95e-d89c5b35d71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración Compensación'])[1]/following::span[3]</value>
      <webElementGuid>1d95257b-6800-4cfc-823d-2b58ea1c41fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[5]</value>
      <webElementGuid>61c172f3-6784-49f9-afb6-3721baeb82d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::span[6]</value>
      <webElementGuid>1797a875-f5fa-49e7-9fd3-24e03ee8d747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Liquidacion Nom']/parent::*</value>
      <webElementGuid>816d17a7-62b6-4eb1-9741-725c800d6fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/ul/li/span</value>
      <webElementGuid>25e83de1-4c52-4695-a635-c2764fd8dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Liquidacion Nom' or . = 'Liquidacion Nom')]</value>
      <webElementGuid>e1f66ad0-e85a-4106-9eaa-f61013079450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
