<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jdbccompensacionds</name>
   <tag></tag>
   <elementGuidId>0e7ae40e-3ebc-47d7-bac9-09edcbe3d71c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//body/div[1]/div/div[2]/div/form[1]/div/div/div/table/tbody/tr[2]/td[1]/span
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>41140a5e-9099-43be-af82-9a5badbb7e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar_estandar</value>
      <webElementGuid>fc378114-ed9c-499d-b4f3-daafa0c8cbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jdbc/compensacionds</value>
      <webElementGuid>69cb130c-3ee6-4aee-9417-96ee1316b620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login:accesosAutorizados_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-odd ui-datatable-selectable fila_tabla_ace ui-state-hover&quot;]/td[2]/span[@class=&quot;valor_campo_estandar_estandar&quot;]</value>
      <webElementGuid>183acf51-ed22-4647-b427-00f4dc48efd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ElegirEmpresa/iframe_Ver ms_7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</value>
      <webElementGuid>50b207f5-17a5-48ae-80c1-7baf5b3087ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='login:accesosAutorizados_data']/tr[2]/td[2]/span</value>
      <webElementGuid>465d0e90-abd7-4678-ae35-f293503e5d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empresa 1'])[2]/following::span[1]</value>
      <webElementGuid>a472c62f-3f6e-4d45-8d64-7ef5379451b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empleado'])[1]/following::span[2]</value>
      <webElementGuid>ad77065c-4721-45b2-b6a1-9d4527765147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empleado'])[2]/preceding::span[1]</value>
      <webElementGuid>cc06962a-8466-44a9-9437-9dca68db8451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[7]</value>
      <webElementGuid>fc4ddc31-49a6-4e8a-96f5-366d10bf915d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jdbc/compensacionds']/parent::*</value>
      <webElementGuid>58efd4b0-dc84-4558-98dc-34369e126064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>798c4508-b948-4dee-a068-460786a734c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jdbc/compensacionds' or . = 'Jdbc/compensacionds')]</value>
      <webElementGuid>94c988a6-a817-4685-8dc8-9d1da1b4cd07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
