<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__form_evaluacion_proceso_seleccion_009171</name>
   <tag></tag>
   <elementGuidId>0e05d4ea-05f1-48ce-b0ab-41bd78692778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>
//*[@id=&quot;form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:4:ingresoTexto&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7c8c0c09-316c-4af0-bf67-f88602fec5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:4:ingresoTexto</value>
      <webElementGuid>c42a0b5a-b411-4e33-8807-f193edd65954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:4:ingresoTexto</value>
      <webElementGuid>a191d302-7b05-44fc-828c-5a51dbb0e8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all caja_texto ui-inputtextarea-resizable ui-state-hover ui-state-focus</value>
      <webElementGuid>ba58a32f-fc07-40f2-83ce-99ee6426b05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>4066fb98-4dce-48b6-a52b-a3aa223bd9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>dc581bea-1cd6-4d21-9d86-02146b0ab5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>54b419db-df0d-4bfa-b1e7-347ef6171667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f1d81f0b-3041-4f11-a947-80f4c4f2cdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9913c4e0-e170-44c3-9495-41de928a0b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53db412e-61c2-4e12-bcc3-c60b0aebf400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ffc8905-4d90-4bcc-8dc7-e9750a36e679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:4:ingresoTexto&quot;)</value>
      <webElementGuid>fdaecd90-523d-4f9b-b264-e0d58a6924da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/Proceso Seleccion/RealizarEvaluacionProcesoSeleccion/RealizarEvaluacionPS/iframe_Evaluaciones del proceso de seleccin_0e352e</value>
      <webElementGuid>ac87529d-9f31-4b89-ae67-b4c2843c4c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:4:ingresoTexto']</value>
      <webElementGuid>4f9525e8-7a5f-4728-8edb-866805b1369a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce']/tbody/tr[5]/td/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td/textarea</value>
      <webElementGuid>bb371077-218e-4d77-859a-8cbe95cb2f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9d5b098e-8bd4-44ce-bece-78f8c3a4a8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:4:ingresoTexto' and @name = 'form_evaluacion_proceso_seleccion:tablaPreguntasEvalProce:4:ingresoTexto']</value>
      <webElementGuid>4b169cdb-1f64-40e2-9db4-1202566e9235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
