<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ifrm_component_A_2</name>
   <tag></tag>
   <elementGuidId>ddfdfb95-8b6b-4f3e-a47e-381285357414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifrm_component_A_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>IFRAME</value>
      <webElementGuid>59775655-fc6a-4b6a-bc6d-54fede260488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1670622088772</value>
      <webElementGuid>93ec9a13-885b-45c4-906d-e91bca81a5e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
