<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ifrm_component_A_3</name>
   <tag></tag>
   <elementGuidId>57977d30-6916-4008-afd5-1aa9b43f1468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifrm_component_A_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>IFRAME</value>
      <webElementGuid>6f8f1d7c-5932-410f-b00f-8df492a1a617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1670623171663</value>
      <webElementGuid>e8bcda7e-4a9d-4390-9c99-9212a0316618</webElementGuid>
   </webElementProperties>
</WebElementEntity>
