<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reporteExternoFormj_idt22</name>
   <tag></tag>
   <elementGuidId>262606fe-2fbf-4eab-8046-42cd00609884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr/td[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a8413a73-3f52-4e4a-aa55-61fbb797caef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1670623201575</value>
      <webElementGuid>5975c943-8944-4a69-a892-9b234982dd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/sinNombre/ifrm_component_A_3</value>
      <webElementGuid>0f419eed-010b-48b5-b52d-9a4c97dadf69</webElementGuid>
   </webElementProperties>
</WebElementEntity>
