<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_tabla_ui-radiobutton-icon</name>
   <tag></tag>
   <elementGuidId>c455e04e-510b-4bbe-929b-cb5b969699de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody/tr/td[4]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5deb784f-9801-4d3b-b8c0-836a17871be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1670624478711</value>
      <webElementGuid>63edad17-9594-46b7-aeef-a979aef5c895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MÓDULOS/sinNombre/ifrm_component_A_3</value>
      <webElementGuid>3ebd3f15-393d-4734-9085-aef75747dd6b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
