<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eliminar</name>
   <tag></tag>
   <elementGuidId>ba76bcd0-175b-4f74-a3a8-56a35ae023df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form[9]/div/div[2]/div[2]/table[2]/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14ba768a-767a-4d6b-8cc2-0775b60af5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupMedioSeleccion_form:j_idt2407</value>
      <webElementGuid>1f4c931a-6d19-4152-9fd8-f2d7462442b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ea648c72-c789-43b4-bc5e-f357c06608e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-eliminar</value>
      <webElementGuid>94ed878d-fc28-4635-b83a-f63be4d29d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;popupMedioSeleccion_form:j_idt2407&quot;,f:&quot;popupMedioSeleccion_form&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>356222c2-a06b-4e91-85ee-94fc441f8151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;popupMedioSeleccion_form:j_idt2407&quot;,type:&quot;dialog&quot;,escape:true,header:&quot;Eliminar&quot;,message:&quot;DESEA CONFIRMAR&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>88a51b1e-3049-4e5d-a1e7-383e59bcb6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>19cd93d4-c8b0-4644-8984-76f0f69c56e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupMedioSeleccion_form:j_idt2407&quot;)</value>
      <webElementGuid>dab115d5-f55c-4a26-859e-5e67f0b64a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='popupMedioSeleccion_form:j_idt2407']</value>
      <webElementGuid>79f5d961-c00b-4ad5-bb50-6f24d9c49f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupMedioSeleccion_form:j_idt2383_content']/div[2]/table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>390eeec6-c5d7-4a03-ad47-4a21d57c4d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Eliminar')])[3]</value>
      <webElementGuid>a5389886-83c8-43dc-9449-170905ae2561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máximo*'])[1]/following::a[2]</value>
      <webElementGuid>392f6d24-db8d-49a9-a9d6-e8161d57c5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mínimo*'])[1]/following::a[2]</value>
      <webElementGuid>b1ccc31f-46f4-484e-838b-34a6543538d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identificación'])[1]/preceding::a[2]</value>
      <webElementGuid>b77a1051-4d80-44fc-8303-af4215ddf42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[1]/preceding::a[2]</value>
      <webElementGuid>8c2adc20-efa3-450c-936f-da2a4ea7005f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[84]</value>
      <webElementGuid>cbff5061-2294-4cc7-8cf1-e036016eba56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[8]/div/div[2]/div[2]/table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>eaed1f72-69c4-4b11-9707-1bf0af2dea42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'popupMedioSeleccion_form:j_idt2407' and @href = '#' and (text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>ac6b2623-9ff4-4858-a80a-47c00e9e4c19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
